import Icon from '../components/Icon';
import { useMutation, useResource } from './api';
import type { Me, Role } from './types';
import { roleLabels } from './types';
import { ErrorBox, Loading, MutationStatus, Panel } from './UI';

export function AuthPage({path, me, message}: {path: string; me?: Me; message?: string}) {
  const parameters = new URLSearchParams(window.location.search);
  const token = parameters.get('invitation') ?? parameters.get('token');
  const invitation = useResource<{displayName: string; invitationEmail: string; companyName: string; branchName: string; role: Role; expiresAt: string}>(path === '/account/activate' && token ? `/auth/invitations/${encodeURIComponent(token)}` : null);
  const loginError = new URLSearchParams(window.location.search).get('error')?.toLowerCase();
  const errors: Record<string, string> = {auth_not_configured: 'Googleログインの接続設定がまだありません。運営者に設定を依頼してください。', auth_policy_required: 'Googleから二段階認証の検証情報を取得できません。会社管理者は検証済みの二段階認証が必要です。Google側の設定・サービス連携設定を運営者に確認してください。', access_denied: 'Googleログインがキャンセルされました。', not_invited: 'このGoogleアカウントには利用許可がありません。会社管理者に招待を依頼してください。', suspended: 'アプリの利用が停止されています。会社管理者にお問い合わせください。', invitation_invalid: '招待リンクが無効です。会社管理者に再招待を依頼してください。', identity_mismatch: '招待したGoogleメールと異なります。本人のアカウントでログインしてください。'};
  const returnTo = path === '/guard/login' ? '/guard' : '/';
  const start = `/api/auth/google/start?returnTo=${encodeURIComponent(returnTo)}${path === '/account/activate' && token ? `&invitation=${encodeURIComponent(token)}` : ''}`;
  return <main className="live-auth"><a className="live-auth-brand" href="/login"><Icon name="shield" size={36} />KEIBI<span>クラウド管制</span></a><section className="live-auth-card">
    {path === '/account/reset' ? <><h1>Googleアカウントの回復</h1><p>本人認証とGoogleの二段階認証はGoogleで管理します。会社のWorkspaceをご利用の場合はWorkspace管理者にも連絡してください。</p><a className="primary-button" href="https://accounts.google.com/signin/recovery" target="_blank" rel="noreferrer">Googleの回復手順を開く</a><p>アプリへの所属・利用停止・Google連携変更は会社管理者が確認します。会社管理者本人の連携変更は別の会社管理者、ほかにいない場合と全管理者が利用できない場合は運営者にお問い合わせください。</p></> : path === '/account/mfa' ? <><h1>Googleの二段階認証</h1><p>会社管理者はGoogle側の二段階認証が必須です。管制担当・閲覧者・警備員にも設定を推奨します。</p><a href="https://myaccount.google.com/security" target="_blank" rel="noreferrer" className="primary-button">Googleのセキュリティ設定</a><p>Googleログインだけでは二段階認証の設定を確認できません。Google側から二段階認証の検証済み情報を取得できない場合、管理者としてログインできません。Googleの二段階認証と連携設定について会社の担当者・運営者にお問い合わせください。</p></> : <><span className="live-eyebrow">SECURE WORKSPACE</span><h1>{path === '/account/activate' ? '招待を確認して利用を開始' : 'Googleでログイン'}</h1><p>会社から利用許可を受けた本人のGoogleアカウントを使用してください。個人Gmailと会社のGoogle Workspaceに対応しています。</p>{message && <p className="live-error" role="alert">{message}</p>}{loginError && <p className="live-error" role="alert">{errors[loginError] ?? 'Googleログインを完了できませんでした。もう一度お試しください。会社・役割は会社管理者の招待に基づいて決まります。'}</p>}
      {path === '/account/activate' && (!token ? <p className="live-error" role="alert">招待リンクが必要です。会社管理者から届いたメールのリンクを開いてください。</p> : invitation.loading ? <Loading /> : invitation.error ? <ErrorBox error={invitation.error} /> : invitation.data ? <div className="live-invitation"><strong>{invitation.data.data.displayName} 様</strong><span>{invitation.data.data.companyName} / {invitation.data.data.branchName}</span><span>{roleLabels[invitation.data.data.role]}</span><span>本人Googleメール: {invitation.data.data.invitationEmail}</span><span>有効期限: {new Date(invitation.data.data.expiresAt).toLocaleString('ja-JP', {timeZone: 'Asia/Tokyo'})}</span><p>この招待は一度だけ利用できます。再招待された場合、以前のリンクは無効です。</p></div> : null)}
      {(path !== '/account/activate' || !!invitation.data) && <a href={start} referrerPolicy="same-origin" className="live-google"><span className="live-google-mark">G</span>{path === '/account/activate' ? '本人のGoogleアカウントで連携する' : 'Googleでログイン'}</a>}{me && <a href={me.role === 'guard' ? '/guard' : '/'} className="secondary-button">{me.displayName}としてホームへ</a>}<p className="live-note">会社管理者はGoogleの二段階認証が必須です。アプリのログインは本人操作なし24時間・ログインから最長1か月で失効します。</p></>}
    <div className="live-auth-links"><a href="/login">ログイン</a><a href="/account/reset">アカウントの回復</a><a href="/account/mfa">二段階認証</a></div>
  </section><a className="live-preview-link" href="/preview">架空データの画面見本を見る</a></main>;
}

export function SecurityPage({me}: {me: Me}) {
  const mutation = useMutation();
  const logout = (all: boolean) => mutation.run(all ? '/auth/logout-all' : '/auth/logout', 'POST', {}, () => {window.dispatchEvent(new Event('keibi-session-expired')); window.location.assign('/login');});
  return <><div className="page-heading"><div><h1>Google連携・セキュリティ</h1><p>本人のGoogle連携とアプリのログイン状態を管理します。</p></div></div><Panel title="現在の利用者"><dl className="live-description"><dt>表示名</dt><dd>{me.displayName}</dd><dt>Googleメール</dt><dd>{me.email}</dd><dt>会社・所属</dt><dd>{me.companyName} / {me.branchName}</dd><dt>役割</dt><dd>{roleLabels[me.role]}</dd></dl></Panel><Panel title="アプリのログアウト"><p className="live-note">この端末のみ、または本人の全端末のアプリセッションを終了できます。全端末を終了するとほかの端末も再ログインが必要です。</p><div className="live-actions"><button className="secondary-button" disabled={mutation.busy} onClick={() => logout(false)}>この端末をログアウト</button><button className="live-danger-button" disabled={mutation.busy} onClick={() => logout(true)}>全端末をログアウト</button></div><MutationStatus mutation={mutation} /></Panel><Panel title="Googleの二段階認証と連携変更"><p className="live-note">{me.role === 'company_admin' ? '会社管理者はGoogle側の二段階認証が必須です。' : 'Google側の二段階認証を推奨します。'}Google連携の変更は会社管理者による本人確認と承認が必要です。会社管理者自身は別の会社管理者、ほかにいなければ運営者に依頼してください。承認後、以前のGoogle連携と全端末のアプリセッションが無効になり、新しいメールへの招待から再連携します。</p><div className="live-actions"><a className="secondary-button" href="https://myaccount.google.com/security" target="_blank" rel="noreferrer">Googleのセキュリティ設定</a><a className="secondary-button" href="/account/reset">回復・連携変更の案内</a></div></Panel></>;
}
