import { useState } from 'react';
import { useResource } from './api';
import type { Me, Officer, PersonalDuty, Snapshot } from './types';
import { Badge, DateRange, ErrorBox, Heading, Loading, Panel } from './UI';
import { baselineDate, formatDate } from './dates';

export function GuardPage({me, path, revision}: {me: Me; path: string; revision: number}) {
  const [from, setFrom] = useState(baselineDate); const [to, setTo] = useState('2026-10-10');
  const [selected, setSelected] = useState(new URLSearchParams(window.location.search).get('duty') ?? '');
  const duties = useResource<PersonalDuty[]>(path === '/guard/profile' ? null : `/me/duties?from=${from}&to=${to}`, revision);
  const officer = useResource<Officer>(path === '/guard/profile' ? '/me/officer' : null, revision);
  const detail = useResource<PersonalDuty>(selected ? `/me/duties/${selected}` : null, revision);
  const site = useResource<Snapshot>(selected && (path === '/guard/site' || path === '/guard/contact') ? `/me/duties/${selected}/site` : null, revision);
  if (path === '/guard/profile') return <><Heading title="マイページ" description="本人の所属・業務情報と資格基本情報を確認できます。" /><Panel title={me.displayName}><dl className="live-description"><dt>会社・所属</dt><dd>{me.companyName} / {me.branchName}</dd><dt>Googleメール</dt><dd>{me.email}</dd></dl>{officer.loading ? <Loading /> : officer.error ? <ErrorBox error={officer.error} retry={officer.reload} /> : officer.data && <><dl className="live-description"><dt>隊員番号</dt><dd>{officer.data.data.code}</dd><dt>氏名</dt><dd>{officer.data.data.name}</dd><dt>在籍状態</dt><dd><Badge state={officer.data.data.status} /></dd><dt>業務電話</dt><dd>{officer.data.data.businessPhone || '未登録'}</dd><dt>業務メール</dt><dd>{officer.data.data.businessEmail || '未登録'}</dd></dl><h3 className="live-detail-name">資格基本情報</h3>{officer.data.data.qualifications?.length ? <ul className="live-history">{officer.data.data.qualifications.map((qualification) => <li key={qualification.qualificationId}><strong>{'name' in qualification ? String(qualification.name) : '資格情報'}</strong><Badge state={qualification.verificationStatus} /><span>{qualification.validFrom ?? '開始指定なし'} 〜 {qualification.validThrough ?? '終了指定なし'}</span></li>)}</ul> : <p className="live-note">資格情報はまだ登録されていません。</p>}</>}<p className="live-note">業務情報の訂正は会社の担当者へ連絡してください。</p><a className="primary-button" href="/account/security">Google連携・ログアウト</a></Panel></>;
  const ended = (duty: PersonalDuty) => duty.state === 'confirmed' && new Date(duty.endsAt).getTime() <= new Date(me.serverTime).getTime();
  const title = path === '/guard' ? `${me.displayName}さんの勤務予定` : path === '/guard/schedule' ? '勤務予定' : path === '/guard/contact' ? '勤務の連絡先' : '担当現場の情報';
  return <><Heading title={title} description="本人に公開された確定勤務を表示します。下書きや他の隊員の情報は表示されません。" /><Panel title="本人の勤務予定"><DateRange from={from} to={to} onFrom={setFrom} onTo={setTo} />{duties.loading ? <Loading /> : duties.error ? <ErrorBox error={duties.error} retry={duties.reload} /> : <div className="live-personal-duties">{duties.data?.data.map((duty) => <article className={`live-personal-duty${selected === duty.slotId ? ' live-personal-selected' : ''}`} key={`${duty.slotId}-${duty.publishedVersionId}`}><div><Badge state={ended(duty) ? 'ended' : duty.state} /><h3>{duty.siteName}</h3><p>{formatDate(duty.startsAt)} 〜 {formatDate(duty.endsAt)}</p><small>勤務日 {duty.dutyDate}</small></div><div className="live-actions"><button className="secondary-button" type="button" aria-pressed={selected === duty.slotId} onClick={() => {setSelected(duty.slotId); window.history.replaceState(null, '', `${path}?duty=${duty.slotId}`);}}>勤務の詳細</button>{duty.state === 'confirmed' && !ended(duty) && <a href={`/guard/site?duty=${duty.slotId}`} className="primary-button">集合場所・指示</a>}</div></article>)}{!duties.data?.data.length && <p className="live-note">この期間に公開された本人の勤務予定はありません。</p>}</div>}</Panel>{selected && <Panel title="選択した勤務の詳細">{detail.loading ? <Loading /> : detail.error ? <ErrorBox error={detail.error} retry={detail.reload} /> : detail.data && <><h3 className="live-detail-name">{detail.data.data.siteName}</h3><Badge state={ended(detail.data.data) ? 'ended' : detail.data.data.state} /><p className="live-note">{formatDate(detail.data.data.startsAt)} 〜 {formatDate(detail.data.data.endsAt)}</p>{detail.data.data.state !== 'confirmed' && <p className="live-note">この勤務は取消または担当解除になっています。集合場所や指示は公開されません。会社の担当者にご確認ください。</p>}</>}{(path === '/guard/site' || path === '/guard/contact') && (site.loading ? <Loading /> : site.error ? <ErrorBox error={site.error} retry={site.reload} /> : site.data && <dl className="live-description"><dt>所在地</dt><dd>{site.data.data.location}</dd><dt>集合場所</dt><dd>{site.data.data.meetingPoint || '未登録'}</dd><dt>勤務指示</dt><dd>{site.data.data.instructions || '未登録'}</dd><dt>業務窓口</dt><dd>{site.data.data.contactName || '未登録'}</dd><dt>業務電話</dt><dd>{site.data.data.businessPhone || '未登録'}</dd></dl>)}{path === '/guard/schedule' && detail.data?.data.state === 'confirmed' && !ended(detail.data.data) && <a className="primary-button" href={`/guard/site?duty=${selected}`}>集合場所・指示・連絡先を見る</a>}</Panel>}<p className="live-note">勤務情報は公開期間内に閲覧できます。勤務の変更・取消や緊急時は、会社の連絡手順で担当者に連絡してください。</p></>;
}
