export type Role = 'company_admin' | 'dispatcher' | 'viewer' | 'guard';
export interface Me { userId: string; membershipId: string; companyId: string; branchId: string; role: Role; officerId: string | null; displayName: string; email: string; companyName: string; branchName: string; csrfToken: string; serverTime: string }
export interface Branch { id: string; code: string; name: string; kind: 'headquarters' | 'branch'; status: string; officerLimit: number; version: number; officerCount?: number }
export interface Qualification { id: string; code: string; name: string; status: 'active' | 'inactive'; version: number }
export interface OfficerQualification { qualificationId: string; verificationStatus: 'unverified' | 'verified' | 'invalid'; validFrom: string | null; validThrough: string | null }
export interface Officer { id: string; code: string; name: string; branchId: string; status: 'active' | 'leave' | 'retired'; businessPhone?: string | null; businessEmail?: string | null; employmentType?: string | null; serviceArea?: string | null; internalMemo?: string | null; version: number; qualifications: OfficerQualification[] }
export interface Client { id: string; code: string; name: string; status: 'active' | 'inactive'; contactName?: string | null; businessPhone?: string | null; businessEmail?: string | null; branchIds?: string[]; version: number }
export interface Site { id: string; code: string; name: string; branchId: string; clientId: string; securityType: 'traffic' | 'facility'; location: string; meetingPoint?: string | null; status: 'planned' | 'active' | 'paused' | 'closed'; instructions?: string | null; internalMemo?: string | null; contractFrom?: string | null; contractThrough?: string | null; contactName?: string | null; businessPhone?: string | null; version: number }
export interface Snapshot { name: string; location: string; meetingPoint: string | null; instructions: string | null; contactName: string | null; businessPhone: string | null }
export interface Revision { id: string; number: number; state: string; dutyDate: string; startsAt: string; endsAt: string; requiredCount: number; assignments: {officerId: string; isLeader: boolean; officerName?: string}[]; qualificationRequirements: {qualificationId: string; requiredQualifiedCount: number}[]; siteSnapshot: Snapshot; availabilityCheck: {confirmed: boolean; note?: string}; travelRestCheck: {confirmed: boolean; note?: string}; reason?: string; warnings?: {code: string; shortageCount?: number; officerId?: string; qualificationId?: string}[] }
export interface Duty { id: string; branchId: string; siteId: string; version: number; state: 'draft' | 'confirmed' | 'cancelled'; draft: Revision | null; published: Revision | null }
export interface PersonalDuty { slotId: string; publishedVersionId: string; dutyDate: string; startsAt: string; endsAt: string; siteName: string; state: 'confirmed' | 'cancelled' | 'removed' }
export interface Member { id: string; userId: string; displayName: string; invitationEmail: string; googleEmail: string | null; branchId: string; branchName: string; role: Role; officerId: string | null; status: 'active' | 'suspended'; version: number; invitationDelivery?: 'sent' | 'pending' | 'failed' | null }
export interface Summary { officerCount: number; siteCount: number; publishedSlotCount: number; publishedAssignedCount: number; publishedRequiredCount: number; publishedShortageCount: number; draftSlotCount: number; draftShortageCount: number }
export interface Envelope<T> { data: T; page?: number; pageSize?: number; total?: number }
export const roleLabels: Record<Role, string> = { company_admin: '会社管理者', dispatcher: '管制担当', viewer: '閲覧者', guard: '警備員' };
export const stateLabels: Record<string, string> = { active: '在籍 / 利用中', leave: '休職', retired: '退職', inactive: '利用停止', planned: '準備中', paused: '休止中', closed: '終了', ended: '終了済み（勤務概要）', draft: '下書き・本人非公開', confirmed: '確定・公開中', cancelled: '取消済み', removed: '担当解除', suspended: '利用停止', verified: '確認済み', unverified: '未確認', invalid: '無効' };
