import type { FormEvent, ReactNode } from 'react';
import { ApiError } from './api';
import type { Mutation } from './api';
import { stateLabels } from './types';

export function Heading({title, description, children}: {title: string; description: string; children?: ReactNode}) { return <div className="page-heading"><div><div className="page-eyebrow"><span className="live-dot" />KEIBI WORKSPACE</div><h1>{title}</h1><p>{description}</p></div><div className="live-actions">{children}</div></div>; }
export function Panel({title, children, actions}: {title?: string; children: ReactNode; actions?: ReactNode}) { return <section className="panel live-panel">{title && <div className="panel-heading"><h2>{title}</h2>{actions}</div>}<div className="live-panel-body">{children}</div></section>; }
export function ErrorBox({error, retry}: {error: Error; retry?: () => void}) { return <div className="live-error" role="alert"><strong>{error.message}</strong>{error instanceof ApiError && <small>{error.code}{error.requestId ? ` / お問い合わせ番号: ${error.requestId}` : ''}</small>}{retry && <button className="secondary-button" type="button" onClick={retry}>再読み込み</button>}</div>; }
export function Loading() { return <p className="live-loading" role="status">保存データを読み込んでいます…</p>; }
export function MutationStatus({mutation}: {mutation: Mutation}) { return <>{mutation.busy && <p role="status" className="live-notice">処理しています…</p>}{mutation.error && <ErrorBox error={mutation.error} />}{mutation.notice && <p role="status" className="live-notice">{mutation.notice}</p>}{mutation.uncertain && <div className="live-actions"><button type="button" className="secondary-button" disabled={mutation.busy} onClick={() => void mutation.recover()}>保存結果を確認</button><button type="button" className="secondary-button" disabled={mutation.busy} onClick={mutation.retry}>同じ操作を再送</button></div>}</>; }
export function Badge({state}: {state: string}) { return <span className={`live-badge live-badge-${state}`}>{stateLabels[state] ?? state}</span>; }
export function Field({label, name, value, onChange, type = 'text', required = false, disabled = false, maxLength = 200, min, max, hint}: {label: string; name: string; value: string | number; onChange: (value: string) => void; type?: string; required?: boolean; disabled?: boolean; maxLength?: number; min?: number | string; max?: number | string; hint?: string}) { return <label className="live-field"><span>{label}{required && <small>必須</small>}</span><input name={name} value={value} onChange={(event) => onChange(event.target.value)} type={type} required={required} disabled={disabled} maxLength={maxLength} min={min} max={max} />{hint && <em>{hint}</em>}</label>; }
export function Textarea({label, name, value, onChange, required = false}: {label: string; name: string; value: string; onChange: (value: string) => void; required?: boolean}) { return <label className="live-field live-wide"><span>{label}{required && <small>必須</small>}</span><textarea name={name} value={value} onChange={(event) => onChange(event.target.value)} maxLength={4000} rows={3} required={required} /></label>; }
export function Select({label, name, value, onChange, children, disabled = false, required = false}: {label: string; name: string; value: string; onChange: (value: string) => void; children: ReactNode; disabled?: boolean; required?: boolean}) { return <label className="live-field"><span>{label}{required && <small>必須</small>}</span><select name={name} value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled} required={required}>{children}</select></label>; }
export function Check({label, checked, onChange, disabled = false}: {label: string; checked: boolean; onChange: (checked: boolean) => void; disabled?: boolean}) { return <label className="live-check"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span>{label}</span></label>; }
export function Form({children, mutation, onSubmit, back, submit = '保存する'}: {children: ReactNode; mutation: Mutation; onSubmit: () => void; back: string; submit?: string}) { const submitForm = (event: FormEvent) => {event.preventDefault(); onSubmit();}; return <form onSubmit={submitForm}><fieldset disabled={mutation.busy || mutation.uncertain} className="live-fieldset"><div className="live-form-grid">{children}</div><div className="live-form-footer"><a className="secondary-button" href={back}>一覧に戻る</a><button className="primary-button" type="submit">{mutation.busy ? '保存中…' : submit}</button></div></fieldset><MutationStatus mutation={mutation} /></form>; }
export function DateRange({from, to, onFrom, onTo}: {from: string; to: string; onFrom: (value: string) => void; onTo: (value: string) => void}) { return <div className="live-actions"><Field label="開始日" name="from" value={from} type="date" onChange={onFrom} /><Field label="終了日" name="to" value={to} type="date" onChange={onTo} /></div>; }
