FROM node:24-alpine

WORKDIR /app
RUN chown node:node /app

USER node

COPY --chown=node:node package.json package-lock.json ./
COPY --chown=node:node apps/frontend/package.json ./apps/frontend/package.json
COPY --chown=node:node apps/backend/package.json ./apps/backend/package.json
RUN npm ci

COPY --chown=node:node . .

EXPOSE 5173 3000

CMD ["npm", "run", "dev", "--workspace", "@keibi/backend"]
