import { useState } from 'react';
import Icon from '../../components/Icon';
import { GuardBadge, GuardCard, GuardEmpty, GuardFormNote, GuardHeading, GuardLink, GuardMockButton } from '../../components/GuardUI';
import { guardCompany, guardNotices, guardOfficer, guardSite } from '../../data/guardPortal';

export function GuardNoticesPage() {
  const [filter, setFilter] = useState('all');
  const [read, setRead] = useState<string[]>(guardNotices.filter((notice) => !notice.unread).map((notice) => notice.id));
  const [selected, setSelected] = useState(new URLSearchParams(window.location.search).get('notice') ?? guardNotices[0].id);
  const visible = guardNotices.filter((notice) => filter !== 'unread' || !read.includes(notice.id));
  const detail = visible.find((notice) => notice.id === selected) ?? visible[0];
  return <><GuardHeading eyebrow="MESSAGES FOR YOU" title="お知らせ" description="会社・管制・担当現場からの連絡を確認できます。" />
    <div className="gp-tabs" role="group" aria-label="お知らせの絞り込み">{[{ id: 'all', text: `すべて ${guardNotices.length}` }, { id: 'unread', text: `未読 ${guardNotices.filter((notice) => !read.includes(notice.id)).length}` }].map((item) => <button type="button" key={item.id} className={filter === item.id ? 'gp-selected' : ''} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)}>{item.text}</button>)}</div>
    <div className="gp-two-columns"><GuardCard title="届いた連絡" icon="bell"><div className="gp-selectable-list">{visible.map((notice) => <button type="button" key={notice.id} className={detail?.id === notice.id ? 'gp-selected' : ''} aria-pressed={detail?.id === notice.id} onClick={() => setSelected(notice.id)}><div><GuardBadge tone={!read.includes(notice.id) ? 'blue' : 'gray'}>{!read.includes(notice.id) ? '未読' : '確認済み'}</GuardBadge><small>{notice.date}</small></div><strong>{notice.title}</strong><span>{notice.category} / {notice.sender}</span></button>)}</div>{!visible.length && <GuardEmpty text="未読のお知らせはありません。" />}</GuardCard>
      {detail && <GuardCard title={detail.category} icon="message"><div className="gp-notice-detail-meta"><span>{detail.sender}</span><time>{detail.date}</time></div><h3 className="gp-notice-title">{detail.title}</h3><p className="gp-body-copy">{detail.body}</p>{detail.site && <GuardLink href="/guard/site" secondary icon="map-pin">関連する現場情報</GuardLink>}<div className="gp-space-top"><button type="button" className="gp-button" disabled={read.includes(detail.id)} onClick={() => setRead((previous) => [...previous, detail.id])}><Icon name="check" size={17} />{read.includes(detail.id) ? '確認済み' : '確認済みにする（プレビュー）'}</button></div><p className="gp-muted gp-space-top">確認状態はこの画面内だけで変わります。会社への確認通知は送信されません。</p></GuardCard>}</div></>;
}

export function GuardEducationPage() {
  return <><GuardHeading eyebrow="TRAINING & LICENSES" title="教育・資格" description="自分の受講記録、教育の案内、保有資格を確認できます。" />
    <div className="gp-two-columns"><GuardCard title="次の教育の案内" icon="calendar"><GuardBadge tone="blue">受講予定の表示例</GuardBadge><div className="gp-training-date"><strong>10<small>月</small>17<small>日（土）</small></strong><span>09:00 — 12:00</span></div><h3>10月 安全教育・現場対応研修</h3><dl className="gp-facts"><div><dt>会場</dt><dd>本社会議室（架空の会場）</dd></div><div><dt>内容</dt><dd>誘導時の安全確認、苦情対応、事故の報告手順</dd></div><div><dt>持ち物</dt><dd>筆記用具・資格者証</dd></div></dl><GuardMockButton>参加予定を回答（モック）</GuardMockButton><p className="gp-muted gp-space-top">研修案内は独立した表示例です。勤務予定・管理画面に予定は登録されません。</p></GuardCard>
      <GuardCard title="保有資格" icon="shield">{guardOfficer.qualifications.map((qualification) => <div className="gp-license" key={qualification}><span><Icon name="shield" size={32} /></span><div><GuardBadge>登録済みの表示例</GuardBadge><h3>{qualification}</h3><p>隊員ID {guardOfficer.id}</p></div></div>)}<p className="gp-muted gp-space-top">資格の正式な証明書・有効性確認は未実装です。</p><GuardLink href="/guard/contact" secondary>資格情報の変更を相談</GuardLink></GuardCard></div>
    <div className="gp-two-columns"><GuardCard title="受講記録" icon="check-circle"><div className="gp-training-history"><span className="gp-task-icon"><Icon name="check-circle" size={24} /></span><div><strong>教育受講記録</strong><p>受講日：{guardOfficer.educationDate?.replaceAll('-', '/') ?? '未登録'}</p><span>隊員管理のサンプルと共通</span></div><GuardBadge tone="gray">記録あり</GuardBadge></div></GuardCard><GuardCard title="現場で確認する資料" icon="download"><div className="gp-document-list">{['交通誘導の基本手順', '事故・トラブル報告の手順', '勤務前の持ち物チェック'].map((title) => <div key={title}><Icon name="shield" size={18} /><strong>{title}</strong><GuardMockButton secondary>開く（モック）</GuardMockButton></div>)}</div><p className="gp-muted gp-space-top">資料名の表示例です。ファイルの閲覧・ダウンロードは行いません。</p></GuardCard></div></>;
}

export function GuardProfilePage() {
  const [inApp, setInApp] = useState(true);
  const [email, setEmail] = useState(false);
  return <><GuardHeading eyebrow="MY ACCOUNT" title="マイページ" description="所属情報、連絡先、通知の受け取り方を確認できます。" />
    <div className="gp-profile-card"><span className="gp-avatar">田</span><div><span className="gp-eyebrow">OFFICER PROFILE</span><h2>{guardOfficer.name}</h2><p>{guardCompany.displayName} / {guardCompany.branchName} / {guardOfficer.id}</p></div><GuardBadge>在籍・{guardOfficer.employment}</GuardBadge></div>
    <div className="gp-two-columns"><GuardCard title="基本情報・連絡先" icon="users"><div className="gp-form-grid"><label className="gp-field">氏名<input value={guardOfficer.name} readOnly /></label><label className="gp-field">隊員ID<input value={guardOfficer.id} readOnly /></label><label className="gp-field gp-field-full">電話番号<input type="tel" defaultValue={guardOfficer.phone} /></label><label className="gp-field gp-field-full">メールアドレス<input type="email" defaultValue={guardOfficer.email} /></label><label className="gp-field gp-field-full">対応エリア<input value={guardOfficer.area} readOnly /></label></div><p className="gp-muted gp-space-top">氏名・所属・資格などの変更は管制へ連絡してください。</p><GuardFormNote /><GuardMockButton>連絡先を保存（モック）</GuardMockButton></GuardCard>
      <div className="gp-stack"><GuardCard title="通知の受け取り方" icon="bell"><label className="gp-setting-row"><span><strong>アプリ内のお知らせ</strong><small>配置・勤務・現場の連絡</small></span><input type="checkbox" checked={inApp} onChange={(event) => setInApp(event.target.checked)} /></label><label className="gp-setting-row"><span><strong>メール通知</strong><small>登録したメールアドレスへの連絡</small></span><input type="checkbox" checked={email} onChange={(event) => setEmail(event.target.checked)} /></label><GuardMockButton secondary>通知設定を保存（モック）</GuardMockButton><p className="gp-muted gp-space-top">通知配信や端末への通知許可の要求は行いません。</p></GuardCard><GuardCard title="アカウント・サポート" icon="shield"><p className="gp-body-copy">この画面は{guardOfficer.name}の固定サンプルです。実際のアカウント作成・認証は未実装です。</p><div className="gp-account-links"><GuardLink href="/guard/contact" secondary icon="headphones">連絡先・ヘルプ</GuardLink><GuardLink href="/guard/login" secondary icon="shield">ログイン画面の表示例</GuardLink></div></GuardCard></div></div></>;
}

export function GuardContactPage() {
  const [faq, setFaq] = useState<string | null>(null);
  const faqs = [
    { title: '勤務先や集合場所を確認したい', body: '「勤務予定」から配置された勤務を確認し、「現場情報」で集合場所・業務指示を見てください。翌日以降の配置待ちは、管制からの連絡をお待ちください。' },
    { title: '上番・下番の時刻を間違えた', body: '「各種申請」で申請種別を「打刻修正」にし、対象日・修正希望時刻・理由を入力します。このモックでは申請や打刻の更新は行われません。' },
    { title: '勤務できなくなった・到着が遅れそう', body: '管制へ直接連絡し、必要に応じて休暇や勤務変更を申請してください。このモックの連絡先は架空で、電話・メッセージ送信は行いません。' },
    { title: '入力した内容が消えた', body: '入力・チェック・確認状態は画面内だけのプレビューです。ページ移動や再読み込みで初期値に戻ります。' },
  ];
  return <><GuardHeading eyebrow="CONTACT & HELP" title="連絡先・ヘルプ" description="勤務中の相談先と、よくある操作を確認できます。" />
    <div className="gp-two-columns"><GuardCard title="管制への連絡" icon="headphones"><div className="gp-contact-row"><span className="gp-avatar">田</span><div><strong>{guardCompany.contact}</strong><small>{guardCompany.displayName} / {guardCompany.branchName}</small></div><GuardBadge tone="blue">管制担当</GuardBadge></div><dl className="gp-facts"><div><dt>電話番号</dt><dd>{guardCompany.phone}</dd></div><div><dt>メール</dt><dd>{guardCompany.email}</dd></div></dl><div className="gp-actions"><GuardMockButton><Icon name="phone" size={17} />電話する（モック）</GuardMockButton><GuardMockButton secondary><Icon name="message" size={17} />連絡する（モック）</GuardMockButton></div><p className="gp-muted gp-space-top">連絡先は架空です。発信・メール・メッセージ送信は行いません。</p></GuardCard>
      <GuardCard title="本日の現場担当者" icon="building"><h3>{guardSite.name}</h3><dl className="gp-facts"><div><dt>担当者</dt><dd>{guardSite.contact}</dd></div><div><dt>電話番号</dt><dd>{guardSite.phone}</dd></div><div><dt>集合場所</dt><dd>{guardSite.meeting}</dd></div></dl><GuardLink href="/guard/site" secondary icon="map-pin">現場情報を見る</GuardLink></GuardCard></div>
    <GuardCard title="よくある質問" icon="help"><div className="gp-faq">{faqs.map((item, index) => <div key={item.title}><button type="button" aria-expanded={faq === item.title} aria-controls={`gp-faq-${index}`} onClick={() => setFaq(faq === item.title ? null : item.title)}><strong>{item.title}</strong><Icon name={faq === item.title ? 'chevron-down' : 'plus'} size={19} /></button><div id={`gp-faq-${index}`} hidden={faq !== item.title}><p>{item.body}</p></div></div>)}</div></GuardCard><div className="gp-info-strip"><Icon name="shield" size={20} /><p>緊急時の連絡手順・対応方法は、実際の会社の運用に合わせて今後設定します。</p></div></>;
}

export function GuardLoginPage() {
  const [visible, setVisible] = useState(false);
  return <div className="gp-login-grid"><section className="gp-login-intro"><span className="gp-eyebrow">YOUR DAY, CONNECTED.</span><h1>今日の現場を、<br />安心して始めよう。</h1><p>勤務予定、現場へのアクセス、日々の報告。<br />必要な情報を、手のひらに。</p><div className="gp-login-visual" aria-hidden="true"><span className="gp-login-orbit" /><span className="gp-login-shield"><Icon name="shield" size={85} /></span><span className="gp-login-float gp-login-float-a"><Icon name="calendar" size={22} />勤務予定を確認</span><span className="gp-login-float gp-login-float-b"><Icon name="check-circle" size={22} />現場とつながる</span></div><span className="gp-login-company">{guardCompany.displayName} · 警備員ポータル</span></section>
    <GuardCard title="警備員ログイン" icon="shield" className="gp-login-card"><p className="gp-body-copy">会社から案内されたアカウントで利用する画面の表示例です。</p><div className="gp-form-grid gp-space-top"><label className="gp-field gp-field-full">会社コード<input autoComplete="off" placeholder="例：TEN-001" /></label><label className="gp-field gp-field-full">メールアドレス<input type="email" autoComplete="off" placeholder="例：g004@example.invalid" /></label><div className="gp-field gp-field-full"><label htmlFor="gp-login-password">パスワード</label><span className="gp-password"><input id="gp-login-password" type={visible ? 'text' : 'password'} autoComplete="off" placeholder="パスワードの表示例" /><button type="button" aria-pressed={visible} onClick={() => setVisible(!visible)}>{visible ? '隠す' : '表示'}</button></span></div></div><p className="gp-form-note">実際の認証は行いません。入力内容は送信されず、サンプル利用者で画面を開きます。</p><GuardLink href="/guard" icon="arrow-right">モック画面を開く</GuardLink><GuardMockButton secondary>パスワード再設定（モック）</GuardMockButton><div className="gp-login-user"><span className="gp-avatar">田</span><div><strong>サンプル利用者：{guardOfficer.name}</strong><small>{guardCompany.branchName} / 隊員ID {guardOfficer.id}</small></div></div></GuardCard></div>;
}
