import Icon from '../../components/Icon';
import { GuardBadge, GuardCard, GuardHeading, GuardLink } from '../../components/GuardUI';
import { guardChecklist, guardNotices, guardOfficer, guardPlacement, guardRequests, guardSite, guardToday } from '../../data/guardPortal';

export default function GuardHomePage() {
  return <>
    <GuardHeading eyebrow="GOOD MORNING" title="おはようございます、田中さん" description="今日の勤務と、確認が必要な連絡をチェックしましょう。" action={<span className="gp-date"><Icon name="calendar" size={17} />2026年10月4日（日）</span>} />
    <div className="gp-home-grid"><section className="gp-duty-hero"><div className="gp-hero-top"><span><span className="gp-live-dot" />TODAY'S DUTY</span><GuardBadge>勤務中</GuardBadge></div><p className="gp-hero-date">10月4日（日）・{guardSite.category}</p><h2>{guardSite.name}</h2><p className="gp-hero-client">{guardSite.client}</p><div className="gp-hero-hours">{guardToday.scheduledStart}<span>—</span>{guardToday.scheduledEnd}<small>休憩予定 {guardToday.breakMinutes}分</small></div><div className="gp-hero-meeting"><Icon name="map-pin" size={19} /><div><small>集合場所</small><strong>{guardSite.meeting}</strong></div></div><div className="gp-hero-bottom"><span><Icon name="users" size={16} />配置 {guardPlacement.officers.length}名 / あなたは現場責任者</span><a href="/guard/site">現場情報を見る<Icon name="arrow-right" size={17} /></a></div></section>
      <GuardCard title="本日の出退勤" icon="clock" className="gp-home-punch"><div className="gp-punch-state"><span className="gp-live-dot" />上番済み・勤務中</div><div className="gp-punch-time"><strong>{guardToday.clockIn}</strong><span>上番記録</span></div><p>下番予定 <strong>{guardToday.scheduledEnd}</strong><br />休憩は現場の状況に合わせて確認してください。</p><GuardLink href="/guard/attendance" icon="clock">出退勤を確認する</GuardLink><a className="gp-text-link" href="/guard/requests?kind=correction">打刻時刻の修正を申請<Icon name="chevron-right" size={14} /></a></GuardCard></div>
    <div className="gp-alert-strip"><Icon name="bell" size={19} /><div><strong>現場からの連絡が1件届いています</strong><p>工事車両入口の誘導位置を確認してください。</p></div><a href="/guard/notices?notice=GN001" aria-label="現場からの連絡を確認"><Icon name="chevron-right" size={22} /></a></div>
    <div className="gp-quick-grid">{[{ href: '/guard/schedule', title: '勤務予定', text: '次の勤務を確認', icon: 'calendar' }, { href: '/guard/shifts', title: '勤務希望', text: '働ける日を入力', icon: 'edit' }, { href: '/guard/reports/new', title: '日報を書く', text: '今日の業務を報告', icon: 'message' }, { href: '/guard/incident', title: '事故・トラブル', text: '管制への報告', icon: 'alert' }].map((item) => <a className="gp-quick-card" href={item.href} key={item.href}><span><Icon name={item.icon as 'calendar' | 'edit' | 'message' | 'alert'} size={22} /></span><strong>{item.title}</strong><small>{item.text}</small><Icon name="arrow-up-right" size={16} /></a>)}</div>
    <div className="gp-two-columns"><GuardCard title="確認すること" icon="check-circle"><div className="gp-task-list"><a href="/guard/notices?notice=GN001"><span className="gp-task-icon"><Icon name="bell" size={19} /></span><div><strong>現場連絡の確認</strong><small>本日の誘導位置について</small></div><GuardBadge tone="amber">未読</GuardBadge></a><a href="/guard/reports/new"><span className="gp-task-icon"><Icon name="message" size={19} /></span><div><strong>本日の警備日報</strong><small>勤務終了後に記入してください</small></div><GuardBadge tone="gray">未作成</GuardBadge></a><a href="/guard/requests"><span className="gp-task-icon"><Icon name="edit" size={19} /></span><div><strong>{guardRequests[0].title}</strong><small>予定09:00 / 記録09:06</small></div><GuardBadge tone="blue">確認待ち</GuardBadge></a></div></GuardCard>
      <GuardCard title="お知らせ" icon="bell" action={<a className="gp-text-link" href="/guard/notices">すべて見る<Icon name="arrow-right" size={14} /></a>}><div className="gp-notice-list">{guardNotices.slice(0, 2).map((notice) => <a key={notice.id} href={`/guard/notices?notice=${notice.id}`}><div><GuardBadge tone={notice.unread ? 'blue' : 'gray'}>{notice.category}</GuardBadge><time>{notice.date}</time></div><strong>{notice.title}</strong><span>{notice.sender}<Icon name="chevron-right" size={15} /></span></a>)}</div></GuardCard></div>
    <GuardCard title="出発前の持ち物チェック" icon="shield" action={<span className="gp-muted">確認用チェックリスト</span>}><div className="gp-checklist">{guardChecklist.map((item) => <label key={item}><input type="checkbox" />{item}</label>)}</div><p className="gp-muted gp-space-top">{guardOfficer.qualifications.join('・')} / チェックはこの画面内のみ有効です。</p></GuardCard>
  </>;
}
