import { useState } from 'react';
import Icon from '../../components/Icon';
import { GuardBadge, GuardCard, GuardEmpty, GuardFormNote, GuardHeading, GuardLink, GuardMockButton } from '../../components/GuardUI';
import { guardOfficer, guardReports, guardRequests, guardShiftPlan, guardSite, guardToday } from '../../data/guardPortal';
import { reportKinds, reportStatuses } from '../../data/reports';
import { shiftDays, shiftStates } from '../../data/shiftPlanning';
import type { ShiftState } from '../../data/shiftPlanning';

export function GuardShiftsPage() {
  const [days, setDays] = useState<ShiftState[]>([...guardShiftPlan.days]);
  return <><GuardHeading eyebrow="MY AVAILABILITY" title="勤務希望" description="勤務できる日、休みたい日、希望する時間帯を入力してください。" />
    <div className="gp-info-strip"><Icon name="calendar" size={20} /><div><strong>対象期間：2026年10月4日（日）— 10月10日（土）</strong><p>配置済みの日は変更できません。変更が必要な場合は管制へ連絡してください。</p></div></div>
    <div className="gp-two-columns gp-form-columns"><GuardCard title="1週間の希望を入力" icon="calendar"><div className="gp-availability-list">{shiftDays.map((day, index) => <div key={day.iso}><div className="gp-availability-date"><strong>{day.label}</strong><span>（{day.weekday}）</span>{index === 0 && <small>基準日</small>}</div>{index === 0 ? <GuardBadge>配置済み {guardToday.scheduledHours}</GuardBadge> : <div className="gp-option-group" role="group" aria-label={`${day.label}の勤務希望`}>{(['available', 'off', 'pending'] as const).map((value) => <button type="button" key={value} className={days[index] === value ? 'gp-selected' : ''} aria-pressed={days[index] === value} onClick={() => setDays((previous) => previous.map((state, dayIndex) => dayIndex === index ? value : state))}>{shiftStates[value].label}</button>)}</div>}</div>)}</div><div className="gp-form-grid gp-space-top"><label className="gp-field">希望開始時刻<input type="time" defaultValue="09:00" /></label><label className="gp-field">希望終了時刻<input type="time" defaultValue="18:00" /></label><label className="gp-field gp-field-full">管制への連絡事項<textarea rows={3} placeholder="勤務時間や対応エリアなどの希望を入力" /></label></div><GuardFormNote /><div className="gp-actions"><GuardMockButton>勤務希望を提出（モック）</GuardMockButton><button type="button" className="gp-button gp-button-secondary" onClick={() => setDays([...guardShiftPlan.days])}>日ごとの希望を元に戻す</button></div></GuardCard>
      <div className="gp-stack"><GuardCard title="入力内容のプレビュー" icon="check-circle"><dl className="gp-facts"><div><dt>勤務可</dt><dd>{days.slice(1).filter((day) => day === 'available').length}日</dd></div><div><dt>休み希望</dt><dd>{days.slice(1).filter((day) => day === 'off').length}日</dd></div><div><dt>未提出</dt><dd>{days.slice(1).filter((day) => day === 'pending').length}日</dd></div></dl><p className="gp-muted">翌日以降の6日間を集計しています。勤務希望は確定した配置ではありません。</p></GuardCard><GuardCard title="管制の確認状況" icon="message"><GuardBadge tone="blue">提出済みの表示例</GuardBadge><p className="gp-body-copy gp-space-top">{guardShiftPlan.note}</p><p className="gp-muted gp-space-top">今回の入力・提出操作で確認状況や管理画面のデータは変わりません。</p><GuardLink href="/guard/requests" secondary>休暇・勤務変更の申請へ</GuardLink></GuardCard></div></div></>;
}

export function GuardRequestsPage() {
  const requested = new URLSearchParams(window.location.search).get('kind');
  const [kind, setKind] = useState(requested === 'correction' ? 'correction' : 'leave');
  const [filter, setFilter] = useState('all');
  const [selected, setSelected] = useState(guardRequests[0].id);
  const visible = guardRequests.filter((request) => filter === 'all' || request.status === '確認待ち');
  const detail = visible.find((request) => request.id === selected) ?? visible[0];
  return <><GuardHeading eyebrow="MY REQUESTS" title="各種申請" description="休暇・勤務変更・打刻修正・経費の申請と確認状況の表示例です。" />
    <div className="gp-two-columns gp-form-columns"><GuardCard title="新しい申請" icon="edit"><div className="gp-form-grid"><label className="gp-field gp-field-full">申請種別<select value={kind} onChange={(event) => setKind(event.target.value)}><option value="leave">休暇申請</option><option value="change">勤務時間の変更</option><option value="correction">打刻修正</option><option value="expense">交通費・経費</option></select></label><label className="gp-field gp-field-full">対象日<input type="date" defaultValue={kind === 'correction' ? '2026-10-04' : '2026-10-05'} key={kind} /></label>{kind === 'leave' && <label className="gp-field gp-field-full">休暇区分<select defaultValue="personal"><option value="personal">私用</option><option value="paid">有給休暇（表示例）</option><option value="other">その他</option></select></label>}{kind === 'change' && <><label className="gp-field">希望開始時刻<input type="time" defaultValue="09:00" /></label><label className="gp-field">希望終了時刻<input type="time" defaultValue="17:00" /></label></>}{kind === 'correction' && <><label className="gp-field">修正する記録<select defaultValue="in"><option value="in">上番</option><option value="out">下番</option><option value="break">休憩</option></select></label><label className="gp-field">修正希望時刻<input type="time" defaultValue="09:00" /></label><p className="gp-muted gp-field-full">10/4の上番記録：{guardToday.clockIn} / 予定：{guardToday.scheduledStart}</p></>}{kind === 'expense' && <><label className="gp-field">金額（円）<input type="number" min="0" step="1" placeholder="例：600" /></label><label className="gp-field">経費区分<select><option>交通費</option><option>備品購入</option><option>その他</option></select></label><label className="gp-field gp-field-full">経路・用途<input placeholder="例：自宅最寄り駅 → 新宿駅（往復）" /></label><label className="gp-field gp-field-full">領収書（ファイル名の確認のみ）<input type="file" accept="image/*,.pdf" /></label></>}<label className="gp-field gp-field-full">理由・補足<textarea rows={4} placeholder="管制担当者が確認できるよう、内容を記入してください" /></label></div><GuardFormNote /><GuardMockButton>申請を提出（モック）</GuardMockButton></GuardCard>
      <div className="gp-stack"><GuardCard title="申請履歴" icon="calendar"><div className="gp-tabs" role="group" aria-label="申請履歴の絞り込み">{[{ id: 'all', text: 'すべて' }, { id: 'pending', text: '確認待ち' }].map((item) => <button type="button" key={item.id} aria-pressed={filter === item.id} className={filter === item.id ? 'gp-selected' : ''} onClick={() => setFilter(item.id)}>{item.text}</button>)}</div><div className="gp-selectable-list">{visible.map((request) => <button type="button" key={request.id} className={detail?.id === request.id ? 'gp-selected' : ''} aria-pressed={detail?.id === request.id} onClick={() => setSelected(request.id)}><div><GuardBadge tone={request.tone}>{request.status}</GuardBadge><small>{request.date}</small></div><strong>{request.title}</strong><span>{request.kind} / {request.id}</span></button>)}</div></GuardCard>{detail && <GuardCard title="選択中の申請" icon="message"><h3>{detail.title}</h3><p className="gp-body-copy gp-space-top">{detail.body}</p><p className="gp-muted gp-space-top">履歴は架空の表示例です。上のフォームから追加・更新はされません。</p></GuardCard>}<div className="gp-info-strip"><Icon name="help" size={19} /><p>急な欠勤・遅れは、申請とあわせて管制へ連絡してください。</p></div><GuardLink href="/guard/contact" secondary icon="phone">管制の連絡先</GuardLink></div></div></>;
}

export function GuardReportsPage() {
  const [kind, setKind] = useState('all');
  const [selected, setSelected] = useState(new URLSearchParams(window.location.search).get('report') ?? guardReports[0]?.id);
  const visible = guardReports.filter((report) => kind === 'all' || report.kind === kind);
  const detail = visible.find((report) => report.id === selected) ?? visible[0];
  return <><GuardHeading eyebrow="MY REPORTS" title="日報・申し送り" description="自分が提出した報告と、管制の確認状況を確認できます。" action={<GuardLink href="/guard/reports/new" icon="plus">日報を書く</GuardLink>} />
    <div className="gp-tabs" role="group" aria-label="報告種別">{[{ id: 'all', text: 'すべて' }, { id: 'daily', text: '警備日報' }, { id: 'handover', text: '申し送り' }, { id: 'incident', text: '事故・苦情' }].map((item) => <button key={item.id} type="button" className={kind === item.id ? 'gp-selected' : ''} aria-pressed={kind === item.id} onClick={() => setKind(item.id)}>{item.text}</button>)}</div>
    <div className="gp-two-columns"><GuardCard title={`提出済みの報告 ${visible.length}件`} icon="message">{visible.length ? <div className="gp-selectable-list">{visible.map((report) => <button type="button" key={report.id} className={detail?.id === report.id ? 'gp-selected' : ''} aria-pressed={detail?.id === report.id} onClick={() => setSelected(report.id)}><div><GuardBadge tone={reportStatuses[report.status].tone}>{reportStatuses[report.status].label}</GuardBadge><small>{report.date.slice(5).replace('-', '/')} {report.time}</small></div><strong>{report.title}</strong><span>{reportKinds[report.kind]} / {report.id}</span></button>)}</div> : <GuardEmpty text="この種別の提出済み報告はありません。" />}<p className="gp-muted gp-space-top">表示対象は{guardOfficer.name}（{guardOfficer.id}）本人の報告です。</p></GuardCard>
      {detail ? <GuardCard title="報告内容・確認履歴" icon="check-circle"><GuardBadge tone={reportStatuses[detail.status].tone}>{reportStatuses[detail.status].label}</GuardBadge><h3 className="gp-space-top">{detail.title}</h3><p className="gp-body-copy gp-space-top">{detail.body}</p><dl className="gp-facts"><div><dt>管制担当</dt><dd>{detail.owner}</dd></div><div><dt>報告者</dt><dd>{detail.reporter}</dd></div><div><dt>次の対応</dt><dd>{detail.nextAction}</dd></div></dl><ol className="gp-timeline">{detail.history.map((entry) => <li key={entry.time}><strong>{entry.time}</strong><div><p>{entry.text}</p></div></li>)}</ol></GuardCard> : <GuardCard title="勤務終了後の報告" icon="edit"><p className="gp-body-copy">業務内容、異常の有無、次の勤務への申し送りを記入してください。</p><GuardLink href="/guard/reports/new">日報の入力画面へ</GuardLink></GuardCard>}</div>
    <div className="gp-alert-strip"><Icon name="alert" size={20} /><div><strong>事故・トラブルの報告</strong><p>急ぎの連絡は管制の連絡先を確認してください。</p></div><a className="gp-text-link" href="/guard/incident">報告画面へ<Icon name="arrow-right" size={15} /></a></div></>;
}

export function GuardReportEditorPage() {
  const [kind, setKind] = useState('daily');
  const [body, setBody] = useState('');
  const [handover, setHandover] = useState('');
  const [abnormal, setAbnormal] = useState('none');
  return <><GuardHeading eyebrow="WRITE A REPORT" title="日報・申し送りの入力" description="今日の業務と、次の隊員に伝えることを記録してください。" action={<GuardLink href="/guard/reports" secondary icon="chevron-left">報告一覧へ</GuardLink>} />
    <div className="gp-two-columns gp-form-columns"><GuardCard title="報告の入力" icon="edit"><div className="gp-form-grid"><label className="gp-field">報告種別<select value={kind} onChange={(event) => setKind(event.target.value)}><option value="daily">警備日報</option><option value="handover">申し送り</option></select></label><label className="gp-field">勤務日<input type="date" defaultValue="2026-10-04" /></label><label className="gp-field gp-field-full">現場<input value={guardSite.name} readOnly /></label><label className="gp-field">上番記録<input value={guardToday.clockIn ?? '未報告'} readOnly /></label><label className="gp-field">下番時刻<input type="time" defaultValue="18:00" /></label><label className="gp-field">休憩時間（分）<input type="number" min="0" max="540" defaultValue="60" /></label><label className="gp-field">異常の有無<select value={abnormal} onChange={(event) => setAbnormal(event.target.value)}><option value="none">異常なし</option><option value="yes">異常あり</option></select></label><label className="gp-field gp-field-full">業務内容<textarea rows={4} value={body} onChange={(event) => setBody(event.target.value)} placeholder="例：工事車両の出入誘導、歩行者への案内を実施" /></label><label className="gp-field gp-field-full">申し送り・特記事項<textarea rows={4} value={handover} onChange={(event) => setHandover(event.target.value)} placeholder="誘導位置の変更、注意事項など" /></label><label className="gp-field gp-field-full">写真・資料（ファイル名の確認のみ）<input type="file" accept="image/*,.pdf" multiple /></label></div>{abnormal === 'yes' && <div className="gp-info-strip"><Icon name="alert" size={18} /><p>詳細は<a href="/guard/incident">事故・トラブル報告</a>にも記入できます。</p></div>}<GuardFormNote /><div className="gp-actions"><GuardMockButton>報告を提出（モック）</GuardMockButton><GuardMockButton secondary>下書きを保存（モック）</GuardMockButton></div></GuardCard>
      <div className="gp-stack"><GuardCard title="内容のプレビュー" icon="message"><GuardBadge tone="blue">{kind === 'daily' ? '警備日報' : '申し送り'}</GuardBadge><h3 className="gp-space-top">{guardSite.name}</h3><p className="gp-muted gp-space-top">報告者：{guardOfficer.name}</p><div className="gp-preview-block"><strong>業務内容</strong><p>{body || '入力した業務内容がここに表示されます。'}</p></div><div className="gp-preview-block"><strong>申し送り</strong><p>{handover || '入力した申し送りがここに表示されます。'}</p></div><GuardBadge tone={abnormal === 'yes' ? 'amber' : 'green'}>{abnormal === 'yes' ? '異常あり' : '異常なし'}</GuardBadge></GuardCard><div className="gp-info-strip"><Icon name="help" size={19} /><p>下番時刻の入力は打刻修正を行いません。提出先・承認方法は本実装時に決定します。</p></div></div></div></>;
}

export function GuardIncidentPage() {
  const [injury, setInjury] = useState('none');
  return <><GuardHeading eyebrow="INCIDENT REPORT" title="事故・トラブル報告" description="発生した事実と、現在の対応状況を管制へ伝える画面です。" />
    <div className="gp-urgent-strip"><Icon name="phone" size={24} /><div><strong>急ぎの連絡は管制へ</strong><p>このモックから連絡は送信されません。まず周囲の安全を確保し、会社の手順に沿って連絡してください。</p></div><GuardLink href="/guard/contact" secondary icon="phone">連絡先を確認</GuardLink></div>
    <div className="gp-two-columns gp-form-columns"><GuardCard title="発生内容" icon="alert"><div className="gp-form-grid"><label className="gp-field gp-field-full">現場<input value={guardSite.name} readOnly /></label><label className="gp-field">発生日<input type="date" defaultValue="2026-10-04" /></label><label className="gp-field">発生時刻<input type="time" defaultValue="09:05" /></label><label className="gp-field">報告種別<select><option>事故</option><option>苦情・ご意見</option><option>ヒヤリハット</option><option>設備・備品の不具合</option><option>その他</option></select></label><label className="gp-field">負傷・物損<select value={injury} onChange={(event) => setInjury(event.target.value)}><option value="none">なし</option><option value="injury">負傷あり</option><option value="damage">物損あり</option><option value="unknown">確認中</option></select></label><label className="gp-field gp-field-full">発生場所<input placeholder="例：工事車両入口の歩道側" /></label><label className="gp-field gp-field-full">何が起きたか<textarea rows={4} placeholder="発生した事実を時系列で記入してください" /></label><label className="gp-field gp-field-full">現在の対応・管制への連絡状況<textarea rows={4} placeholder="現場担当者への共有、誘導位置の変更など" /></label><label className="gp-field gp-field-full">写真・資料（ファイル名の確認のみ）<input type="file" accept="image/*,.pdf" multiple /></label></div><GuardFormNote /><GuardMockButton>報告を送信（モック）</GuardMockButton></GuardCard>
      <div className="gp-stack"><GuardCard title="報告時の確認事項" icon="check-circle"><ul className="gp-bullet-list"><li>いつ・どこで発生したか</li><li>関係者と負傷・物損の有無</li><li>現在の状況と実施した対応</li><li>誰に、いつ連絡したか</li></ul><p className="gp-muted">推測と確認できた事実を分けて記入してください。</p></GuardCard><GuardCard title="自分の報告履歴" icon="message"><GuardBadge tone="blue">確認中</GuardBadge><h3 className="gp-space-top">{guardReports[0].title}</h3><p className="gp-body-copy gp-space-top">{guardReports[0].body}</p><GuardLink href={`/guard/reports?report=${guardReports[0].id}`} secondary>確認履歴を見る</GuardLink></GuardCard></div></div></>;
}
