import { useState } from 'react';
import Icon from '../../components/Icon';
import { GuardBadge, GuardCard, GuardHeading, GuardLink, GuardMockButton } from '../../components/GuardUI';
import { attendanceStatuses, formatDuration } from '../../data/attendance';
import { guardAttendance, guardChecklist, guardOfficer, guardPlacement, guardSchedule, guardSite, guardToday } from '../../data/guardPortal';

export function GuardSchedulePage() {
  const [selected, setSelected] = useState<string>('2026-10-04');
  const day = guardSchedule.find((item) => item.date === selected)!;
  return <><GuardHeading eyebrow="MY SCHEDULE" title="勤務予定" description="自分の配置と勤務時間を確認できます。" action={<GuardLink href="/guard/shifts" secondary icon="edit">勤務希望を入力</GuardLink>} />
    <div className="gp-schedule-summary"><div><span>本日の勤務</span><strong>09:00 — 18:00</strong><small>{guardSite.name}</small></div><div><span>翌日以降の配置</span><strong>調整中</strong><small>確定した勤務は管制から連絡します</small></div><div><span>勤務希望</span><strong>提出済み</strong><small>10/4 — 10/10の表示例</small></div></div>
    <GuardCard title="10月3日 — 10月10日" icon="calendar"><div className="gp-day-picker" role="group" aria-label="勤務日を選択">{guardSchedule.map((item) => <button type="button" key={item.date} onClick={() => setSelected(item.date)} aria-pressed={selected === item.date} className={selected === item.date ? 'gp-selected' : ''}><span>{item.weekday}</span><strong>{Number(item.date.slice(-2))}</strong><small>{item.date === '2026-10-04' ? '基準日' : item.kind === 'confirmed' || item.kind === 'completed' ? '勤務' : '未確定'}</small></button>)}</div></GuardCard>
    <div className="gp-two-columns"><GuardCard title={`${day.date.replaceAll('-', '/')}（${day.weekday}）`} icon="calendar"><GuardBadge tone={day.kind === 'confirmed' ? 'green' : day.kind === 'completed' ? 'gray' : 'amber'}>{day.label}</GuardBadge>{'site' in day ? <div className="gp-selected-duty"><h3>{day.site.name}</h3><p>{day.site.category} / {day.site.client}</p><strong className="gp-big-hours">{day.site.hours}</strong><dl className="gp-facts"><div><dt>集合場所</dt><dd>{day.site.meeting}</dd></div><div><dt>担当</dt><dd>現場責任者</dd></div><div><dt>休憩予定</dt><dd>60分</dd></div></dl><GuardLink href="/guard/site">現場情報を見る</GuardLink></div> : <div className="gp-empty"><Icon name="calendar" size={31} /><h3>勤務先はまだ決まっていません</h3><p>勤務希望と確定した配置は別です。<br />配置が決まり次第、管制から連絡します。</p><GuardLink href="/guard/shifts" secondary>勤務希望を確認</GuardLink></div>}</GuardCard>
      <GuardCard title="勤務の一覧" icon="building"><div className="gp-agenda">{guardSchedule.map((item) => <button key={item.date} type="button" onClick={() => setSelected(item.date)} aria-pressed={selected === item.date} className={selected === item.date ? 'gp-selected' : ''}><span className="gp-agenda-date"><strong>10/{Number(item.date.slice(-2))}</strong><small>{item.weekday}</small></span><span><strong>{'site' in item ? item.site.name : '配置未確定'}</strong><small>{'site' in item ? item.site.hours : '管制からの連絡をお待ちください'}</small></span><Icon name="chevron-right" size={17} /></button>)}</div></GuardCard></div></>;
}

export function GuardSitePage() {
  const [checked, setChecked] = useState(false);
  return <><GuardHeading eyebrow="SITE BRIEFING" title="現場情報" description="集合場所、業務内容、連絡先を勤務前に確認してください。" action={<GuardLink href="/guard/schedule" secondary icon="calendar">勤務予定へ</GuardLink>} />
    <div className="gp-site-heading"><span className="gp-site-icon"><Icon name="traffic" size={30} /></span><div><GuardBadge tone="blue">{guardSite.category}</GuardBadge><h2>{guardSite.name}</h2><p>{guardSite.client} / 現場ID {guardSite.id}</p></div></div>
    <div className="gp-two-columns"><GuardCard title="集合場所・アクセス" icon="map-pin"><div className="gp-map" role="img" aria-label="新宿駅西口から工事車両入口までの位置関係を示す模式図。実際の地図ではありません。"><div className="gp-map-block gp-map-block-a">駅前街区</div><div className="gp-map-block gp-map-block-b">工事区画</div><span className="gp-map-road">西口通り</span><span className="gp-map-station">新宿駅 西口</span><span className="gp-map-route" /><span className="gp-map-pin"><Icon name="map-pin" size={25} /><strong>集合場所</strong></span><small>アクセス模式図 / 実際の地図・経路ではありません</small></div><dl className="gp-facts"><div><dt>所在地</dt><dd>{guardSite.address}</dd></div><div><dt>集合場所</dt><dd>{guardSite.meeting}</dd></div><div><dt>勤務時間</dt><dd>{guardSite.hours} / 休憩予定60分</dd></div></dl><p className="gp-muted">地図・経路案内の外部サービス連携は未実装です。</p></GuardCard>
      <div className="gp-stack"><GuardCard title="業務指示・注意事項" icon="shield"><p className="gp-body-copy">{guardSite.note}</p><div className="gp-instruction"><strong>配置条件</strong><p>{guardSite.condition}</p></div><ul className="gp-bullet-list"><li>上番前に現場担当者と誘導位置を確認。</li><li>交代・休憩時は配置位置と注意点を申し送る。</li><li>変更やトラブルは管制へ連絡。</li></ul><label className="gp-check-row"><input type="checkbox" checked={checked} onChange={(event) => setChecked(event.target.checked)} />業務指示を確認しました（画面内のみ）</label></GuardCard><GuardCard title="現場担当者" icon="phone"><div className="gp-contact-row"><span className="gp-avatar">青</span><div><strong>{guardSite.contact}</strong><small>{guardSite.phone} / 架空の連絡先</small></div></div><GuardLink href="/guard/contact" secondary icon="phone">連絡先を確認</GuardLink></GuardCard></div></div>
    <div className="gp-two-columns"><GuardCard title={`本日の配置隊員 ${guardPlacement.officers.length}名`} icon="users"><div className="gp-roster">{guardPlacement.officers.map((officer) => <div key={officer.id}><span className="gp-avatar">{officer.name.slice(0, 1)}</span><div><strong>{officer.name}{officer.id === guardOfficer.id && <small>（あなた）</small>}</strong><span>{officer.id}</span></div><GuardBadge tone={officer.leader ? 'blue' : 'gray'}>{officer.leader ? '現場責任者' : '隊員'}</GuardBadge></div>)}</div><p className="gp-muted gp-space-top">必要3名に対し配置2名。追加の配置は管制が調整中です。</p></GuardCard><GuardCard title="持ち物・申し送り" icon="message"><div className="gp-checklist gp-checklist-vertical">{guardChecklist.map((item) => <label key={item}><input type="checkbox" />{item}</label>)}</div><a className="gp-text-link gp-space-top" href="/guard/notices?notice=GN001">本日の現場連絡を見る<Icon name="arrow-right" size={15} /></a></GuardCard></div></>;
}

export function GuardAttendancePage() {
  const [tab, setTab] = useState('today');
  return <><GuardHeading eyebrow="TIME & ATTENDANCE" title="出退勤・勤務実績" description="上番・下番の報告と、自分の勤務記録を確認できます。" action={<GuardLink href="/guard/requests?kind=correction" secondary icon="edit">打刻修正を申請</GuardLink>} />
    <div className="gp-tabs" role="group" aria-label="勤怠の表示">{[{ id: 'today', text: '本日の出退勤' }, { id: 'history', text: '勤務実績' }].map((item) => <button type="button" key={item.id} aria-pressed={tab === item.id} className={tab === item.id ? 'gp-selected' : ''} onClick={() => setTab(item.id)}>{item.text}</button>)}</div>
    {tab === 'today' ? <div className="gp-two-columns"><GuardCard title="10月4日（日）の勤務" icon="clock"><div className="gp-clock-display"><GuardBadge>勤務中</GuardBadge><strong>09:30</strong><span>基準日時の表示 / 現在時刻には連動しません</span></div><h3 className="gp-centered">{guardSite.name}</h3><div className="gp-time-pair"><div><span>上番予定</span><strong>{guardToday.scheduledStart}</strong></div><div><span>下番予定</span><strong>{guardToday.scheduledEnd}</strong></div></div><div className="gp-punch-buttons"><button type="button" className="gp-button gp-button-secondary" disabled><Icon name="check-circle" size={18} />上番報告済み {guardToday.clockIn}</button><GuardMockButton><Icon name="clock" size={18} />下番を報告（モック）</GuardMockButton></div><p className="gp-form-note">位置情報の取得・打刻送信は行いません。</p></GuardCard><div className="gp-stack"><GuardCard title="本日の記録" icon="activity"><ol className="gp-timeline"><li><strong>09:00</strong><div><h3>上番予定</h3><p>配置された勤務の開始時刻</p></div></li><li><strong>{guardToday.clockIn}</strong><div><h3>上番記録</h3><p>勤務開始の報告サンプル</p><GuardBadge tone="amber">時刻の確認待ち</GuardBadge></div></li><li className="gp-timeline-future"><strong>—</strong><div><h3>休憩・下番</h3><p>休憩予定60分 / 下番は未報告</p></div></li></ol></GuardCard><GuardCard title="休憩時間" icon="clock"><label className="gp-field">休憩時間（分）<input type="number" min="0" max="540" defaultValue={guardToday.breakMinutes} /></label><GuardMockButton secondary>休憩を記録（モック）</GuardMockButton><p className="gp-muted gp-space-top">入力値は実績や管理画面には反映されません。</p></GuardCard></div></div> : <><div className="gp-info-strip"><Icon name="help" size={18} /><p>10月3日・4日の2日分のサンプルです。未下番の勤務は集計前として表示します。</p></div><GuardCard title="勤務記録" icon="calendar"><div className="gp-table-scroll"><table className="gp-table"><thead><tr><th scope="col">勤務日・現場</th><th scope="col">上番</th><th scope="col">下番</th><th scope="col">休憩</th><th scope="col">実績</th><th scope="col">状態</th></tr></thead><tbody>{[...guardAttendance].reverse().map((record) => <tr key={record.id}><td><strong>{record.date.replaceAll('-', '/')}</strong><span>{record.siteName}</span></td><td>{record.clockIn ?? '—'}</td><td>{record.clockOut ?? '—'}</td><td>{record.breakMinutes}分</td><td>{record.actualMinutes === null ? '集計前' : formatDuration(record.actualMinutes)}</td><td><GuardBadge tone={attendanceStatuses[record.status].tone}>{attendanceStatuses[record.status].label}</GuardBadge></td></tr>)}</tbody></table></div></GuardCard><GuardCard title="記録内容の確認" icon="help"><p className="gp-body-copy">{guardToday.reviewNote}</p><GuardLink href="/guard/requests?kind=correction" secondary>打刻修正の申請画面へ</GuardLink></GuardCard></>}
  </>;
}
