import { useState } from 'react';
import Icon from '../../components/Icon';
import GoogleLoginPreview from '../../components/GoogleLoginPreview';
import { GuardBadge, GuardCard, GuardEmpty, GuardFormNote, GuardHeading, GuardLink, GuardMockButton } from '../../components/GuardUI';
import { guardCompany, guardDutySummaries, guardLoginEmail, guardNotices, guardOfficer } from '../../data/guardPortal';
import { formatDutyDateTime } from '../../data/mockDutySlots';

export function GuardNoticesPage() {
  const [filter, setFilter] = useState('all');
  const [read, setRead] = useState<string[]>(guardNotices.filter((notice) => !notice.unread).map((notice) => notice.id));
  const [selected, setSelected] = useState(new URLSearchParams(window.location.search).get('notice') ?? guardNotices[0].id);
  const visible = guardNotices.filter((notice) => filter !== 'unread' || !read.includes(notice.id));
  const detail = visible.find((notice) => notice.id === selected) ?? visible[0];
  return <><GuardHeading eyebrow="MESSAGES FOR YOU" title="お知らせ" description="会社・管制・担当現場からの連絡を確認できます。" />
    <div className="gp-tabs" role="group" aria-label="お知らせの絞り込み">{[{ id: 'all', text: `すべて ${guardNotices.length}` }, { id: 'unread', text: `未読 ${guardNotices.filter((notice) => !read.includes(notice.id)).length}` }].map((item) => <button type="button" key={item.id} className={filter === item.id ? 'gp-selected' : ''} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)}>{item.text}</button>)}</div>
    <div className="gp-two-columns"><GuardCard title="届いた連絡" icon="bell"><div className="gp-selectable-list">{visible.map((notice) => <button type="button" key={notice.id} className={detail?.id === notice.id ? 'gp-selected' : ''} aria-pressed={detail?.id === notice.id} onClick={() => setSelected(notice.id)}><div><GuardBadge tone={!read.includes(notice.id) ? 'blue' : 'gray'}>{!read.includes(notice.id) ? '未読' : '確認済み'}</GuardBadge><small>{notice.date}</small></div><strong>{notice.title}</strong><span>{notice.category} / {notice.sender}</span></button>)}</div>{!visible.length && <GuardEmpty text="未読のお知らせはありません。" />}</GuardCard>
      {detail && <GuardCard title={detail.category} icon="message"><div className="gp-notice-detail-meta"><span>{detail.sender}</span><time>{detail.date}</time></div><h3 className="gp-notice-title">{detail.title}</h3><p className="gp-body-copy">{detail.body}</p>{detail.site && <p className="gp-muted gp-space-top">現場連絡は次期の独立した表示例です。初回の確定勤務予定とは連動しません。</p>}<div className="gp-space-top"><button type="button" className="gp-button" disabled={read.includes(detail.id)} onClick={() => setRead((previous) => [...previous, detail.id])}><Icon name="check" size={17} />{read.includes(detail.id) ? '確認済み' : '確認済みにする（プレビュー）'}</button></div><p className="gp-muted gp-space-top">確認状態はこの画面内だけで変わります。会社への確認通知は送信されません。</p></GuardCard>}</div></>;
}

export function GuardEducationPage() {
  return <><GuardHeading eyebrow="TRAINING & LICENSES" title="教育・資格" description="自分の受講記録、教育の案内、保有資格を確認できます。" />
    <div className="gp-two-columns"><GuardCard title="次の教育の案内" icon="calendar"><GuardBadge tone="blue">受講予定の表示例</GuardBadge><div className="gp-training-date"><strong>10<small>月</small>17<small>日（土）</small></strong><span>09:00 — 12:00</span></div><h3>10月 安全教育・現場対応研修</h3><dl className="gp-facts"><div><dt>会場</dt><dd>本社会議室（架空の会場）</dd></div><div><dt>内容</dt><dd>誘導時の安全確認、苦情対応、事故の報告手順</dd></div><div><dt>持ち物</dt><dd>筆記用具・資格者証</dd></div></dl><GuardMockButton>参加予定を回答（モック）</GuardMockButton><p className="gp-muted gp-space-top">研修案内は独立した表示例です。勤務予定・管理画面に予定は登録されません。</p></GuardCard>
      <GuardCard title="保有資格" icon="shield">{guardOfficer.qualifications.map((qualification) => <div className="gp-license" key={qualification}><span><Icon name="shield" size={32} /></span><div><GuardBadge>登録済みの表示例</GuardBadge><h3>{qualification}</h3><p>隊員ID {guardOfficer.id}</p></div></div>)}<p className="gp-muted gp-space-top">資格の正式な証明書・有効性確認は未実装です。</p><GuardLink href="/guard/contact" secondary>資格情報の変更を相談</GuardLink></GuardCard></div>
    <div className="gp-two-columns"><GuardCard title="受講記録" icon="check-circle"><div className="gp-training-history"><span className="gp-task-icon"><Icon name="check-circle" size={24} /></span><div><strong>教育受講記録</strong><p>受講日：{guardOfficer.educationDate?.replaceAll('-', '/') ?? '未登録'}</p><span>隊員管理のサンプルと共通</span></div><GuardBadge tone="gray">記録あり</GuardBadge></div></GuardCard><GuardCard title="現場で確認する資料" icon="download"><div className="gp-document-list">{['交通誘導の基本手順', '事故・トラブル報告の手順', '勤務前の持ち物チェック'].map((title) => <div key={title}><Icon name="shield" size={18} /><strong>{title}</strong><GuardMockButton secondary>開く（モック）</GuardMockButton></div>)}</div><p className="gp-muted gp-space-top">資料名の表示例です。ファイルの閲覧・ダウンロードは行いません。</p></GuardCard></div></>;
}

export function GuardProfilePage() {
  const [inApp, setInApp] = useState(true);
  const [email, setEmail] = useState(false);
  return <><GuardHeading eyebrow="MY ACCOUNT" title="マイページ" description="本人の所属・基本情報・基本資格と、Google連携の表示例を確認できます。" />
    <div className="gp-profile-card"><span className="gp-avatar">田</span><div><span className="gp-eyebrow">OFFICER PROFILE</span><h2>{guardOfficer.name}</h2><p>{guardCompany.displayName} / {guardCompany.branchName} / {guardOfficer.id}</p></div><GuardBadge>在籍・{guardOfficer.employment}</GuardBadge></div>
    <div className="gp-two-columns"><GuardCard title="基本情報・業務連絡先（閲覧）" icon="users"><dl className="gp-facts"><div><dt>氏名</dt><dd>{guardOfficer.name}</dd></div><div><dt>隊員ID</dt><dd>{guardOfficer.id}</dd></div><div><dt>所属</dt><dd>{guardCompany.displayName} / {guardCompany.branchName}</dd></div><div><dt>電話番号</dt><dd>{guardOfficer.phone}</dd></div><div><dt>業務メール</dt><dd>{guardOfficer.email}</dd></div><div><dt>対応エリア</dt><dd>{guardOfficer.area}</dd></div></dl><p className="gp-muted">本人情報や連絡先の訂正は、管理者・管制へ依頼してください。</p><GuardLink href="/guard/contact" secondary icon="phone">変更を相談する</GuardLink></GuardCard>
      <div className="gp-stack"><GuardCard title="本人の資格基本情報" icon="shield">{guardOfficer.qualifications.map((qualification) => <div className="gp-license" key={qualification}><span><Icon name="shield" size={28} /></span><div><GuardBadge tone="gray">登録情報の表示例</GuardBadge><h3>{qualification}</h3></div></div>)}<p className="gp-muted gp-space-top">証明書・有効性の正式な確認は、会社の既存の手順で行います。</p></GuardCard><GuardCard title="Google連携" icon="shield"><dl className="gp-facts"><div><dt>Google連携メールの表示例</dt><dd>{guardLoginEmail}</dd></div><div><dt>連携状態</dt><dd>連携済みの表示例</dd></div></dl><p className="gp-muted">業務連絡先とは別の情報です。メールは架空で、Google認証・連携・ログアウトは未実装です。パスワードや二段階認証はGoogle側で管理します。</p><div className="gp-reference-links gp-space-top"><GuardLink href="/account/security?view=guard" secondary icon="shield">Google連携・ログアウトの見本</GuardLink></div><a className="gp-text-link gp-space-top" href="/guard/login">Googleログイン画面の表示例<Icon name="arrow-right" size={14} /></a></GuardCard></div></div>
    <details className="gp-reference-section"><summary>次期の参考モック：連絡先の直接編集・通知設定</summary><div className="gp-two-columns gp-space-top"><GuardCard title="連絡先の編集例" icon="edit"><div className="gp-form-grid"><label className="gp-field gp-field-full">電話番号<input type="tel" defaultValue={guardOfficer.phone} /></label><label className="gp-field gp-field-full">業務メールアドレス<input type="email" defaultValue={guardOfficer.email} /></label></div><GuardFormNote /><GuardMockButton>連絡先を保存（モック）</GuardMockButton></GuardCard><GuardCard title="通知の受け取り方の例" icon="bell"><label className="gp-setting-row"><span><strong>アプリ内のお知らせ</strong><small>配置・勤務・現場の連絡</small></span><input type="checkbox" checked={inApp} onChange={(event) => setInApp(event.target.checked)} /></label><label className="gp-setting-row"><span><strong>メール通知</strong><small>登録したメールアドレスへの連絡</small></span><input type="checkbox" checked={email} onChange={(event) => setEmail(event.target.checked)} /></label><GuardMockButton secondary>通知設定を保存（モック）</GuardMockButton><p className="gp-muted gp-space-top">通知配信や端末への通知許可の要求は行いません。</p></GuardCard></div></details></>;
}

export function GuardContactPage() {
  const [faq, setFaq] = useState<string | null>(null);
  const dutyId = new URLSearchParams(window.location.search).get('duty');
  const duty = guardDutySummaries.find((item) => item.dutyId === dutyId && item.status === 'published');
  const faqs = [
    { title: '勤務先や集合場所を確認したい', body: '「勤務予定」から確定した対象勤務を選び、その勤務の「現場情報」を開いてください。確定予定がない場合は管制へ連絡してください。勤務希望と確定した勤務予定は別です。' },
    { title: '予定が変更・取消になった', body: '勤務予定を確認し、電話などの既存の連絡手段で管制からの案内も確認してください。未確定の改訂案は本人に表示しない案です。アプリ内通知・既読の記録は次期の機能です。' },
    { title: '勤務できなくなった・到着が遅れそう', body: '早めに管制へ直接連絡し、会社の既存の手順で調整してください。システムでの休暇・勤務変更の申請は次期の参考モックです。このモックの連絡先は架空で、電話・メッセージ送信は行いません。' },
    { title: '自分の情報を訂正したい', body: 'マイページで本人の基本情報・業務連絡先・資格を確認し、訂正は管理者または管制に依頼してください。Google連携メールは業務連絡先とは別の情報です。Google連携の変更には本人確認と会社管理者の承認が必要です。古い連携と全端末のアプリログインを失効し、新しい招待で連携します。' },
    { title: '招待の有効期限が切れた', body: '招待は発行から7日間有効です。期限切れや使用済みの場合は会社管理者へ再招待を依頼してください。再招待すると古い招待は無効になります。招待は現在のモックでは表示のみです。' },
    { title: 'Googleでログインできない', body: 'Googleアカウントの回復はGoogle公式の手順で行います。パスワード・確認コード・復旧コードを会社に伝える必要はありません。Googleでログインできても、このシステムを利用できない場合は、招待・所属・利用停止の状況を会社管理者へ確認してください。' },
    { title: 'ログアウトしたい', body: 'マイページの「Google連携・ログアウト」から、このシステムのセッションを終了する想定です。Googleや他サービスのログイン状態は変わりません。現在のモックではログアウトは表示のみです。' },
    { title: '入力した内容が消えた', body: '入力・チェック・確認状態は画面内だけのプレビューです。ページ移動や再読み込みで初期値に戻ります。' },
  ];
  return <><GuardHeading eyebrow="CONTACT & HELP" title="連絡先・ヘルプ" description="勤務中の相談先と、よくある操作を確認できます。" />
    <div className="gp-two-columns"><GuardCard title="管制への連絡" icon="headphones"><div className="gp-contact-row"><span className="gp-avatar">田</span><div><strong>{guardCompany.contact}</strong><small>{guardCompany.displayName} / {guardCompany.branchName}</small></div><GuardBadge tone="blue">管制担当</GuardBadge></div><dl className="gp-facts"><div><dt>電話番号</dt><dd>{guardCompany.phone}</dd></div><div><dt>メール</dt><dd>{guardCompany.email}</dd></div></dl><div className="gp-actions"><GuardMockButton><Icon name="phone" size={17} />電話する（モック）</GuardMockButton><GuardMockButton secondary><Icon name="message" size={17} />連絡する（モック）</GuardMockButton></div><p className="gp-muted gp-space-top">連絡先は架空です。発信・メール・メッセージ送信は行いません。</p></GuardCard>
      <GuardCard title="対象勤務の業務連絡先" icon="building">{duty?.publicDuty ? <><GuardBadge>確定・公開中</GuardBadge><h3 className="gp-space-top">{duty.siteName}</h3><p className="gp-muted">{formatDutyDateTime(duty.startAt)} — {formatDutyDateTime(duty.endAt)}</p><dl className="gp-facts"><div><dt>担当者</dt><dd>{duty.publicDuty.contact}</dd></div><div><dt>電話番号</dt><dd>{duty.publicDuty.phone}</dd></div></dl><GuardLink href={`/guard/site?duty=${duty.dutyId}`} secondary icon="map-pin">この勤務の現場情報</GuardLink></> : <><div className="gp-empty"><Icon name="calendar" size={28} /><p>現場の業務連絡先は、公開された確定勤務を選んで確認してください。終了・取消後の現場詳細は表示しない案です。</p></div><GuardLink href="/guard/schedule" secondary icon="calendar">対象の勤務を選ぶ</GuardLink></>}</GuardCard></div>
    <GuardCard title="よくある質問" icon="help"><div className="gp-faq">{faqs.map((item, index) => <div key={item.title}><button type="button" aria-expanded={faq === item.title} aria-controls={`gp-faq-${index}`} onClick={() => setFaq(faq === item.title ? null : item.title)}><strong>{item.title}</strong><Icon name={faq === item.title ? 'chevron-down' : 'plus'} size={19} /></button><div id={`gp-faq-${index}`} hidden={faq !== item.title}><p>{item.body}</p></div></div>)}</div></GuardCard><div className="gp-info-strip"><Icon name="shield" size={20} /><p>緊急時の連絡手順・対応方法は、実際の会社の運用に合わせて今後設定します。</p></div></>;
}

export function GuardLoginPage() {
  return <div className="gp-login-grid"><section className="gp-login-intro"><span className="gp-eyebrow">YOUR DAY, CONNECTED.</span><h1>今日の現場を、<br />安心して始めよう。</h1><p>勤務予定、現場へのアクセス、日々の報告。<br />必要な情報を、手のひらに。</p><div className="gp-login-visual" aria-hidden="true"><span className="gp-login-orbit" /><span className="gp-login-shield"><Icon name="shield" size={85} /></span><span className="gp-login-float gp-login-float-a"><Icon name="calendar" size={22} />勤務予定を確認</span><span className="gp-login-float gp-login-float-b"><Icon name="check-circle" size={22} />現場とつながる</span></div><span className="gp-login-company">{guardCompany.displayName} · 警備員ポータル</span></section>
    <GuardCard title="Googleで警備員ログイン" icon="shield" className="gp-login-card"><p className="gp-body-copy">会社から招待された本人のGoogleアカウントで利用します。所属・役割・隊員との対応は会社管理者が設定します。</p><div className="gp-space-top"><GoogleLoginPreview /></div><p className="gp-muted gp-space-top">パスワード・確認コードはGoogleの画面で入力します。このシステムでは入力・保管しません。</p><p className="gp-form-note" role="note">Google認証は未実装で、ボタンは表示のみです。画面の確認には、下のモック用リンクを使います。</p><GuardLink href="/guard" icon="arrow-right">固定サンプルのモックを開く</GuardLink><div className="gp-reference-links gp-space-top"><GuardLink href="/account/activate" secondary>招待確認・初回Google連携の見本</GuardLink><GuardLink href="/account/reset" secondary>Googleアカウントの回復案内</GuardLink><a className="gp-text-link" href="/login">管理者・管制のログイン見本<Icon name="arrow-right" size={14} /></a></div><div className="gp-login-user"><span className="gp-avatar">田</span><div><strong>サンプル利用者：{guardOfficer.name}</strong><small>{guardCompany.branchName} / 隊員ID {guardOfficer.id}</small></div></div></GuardCard></div>;
}
