import Icon from '../../components/Icon';
import type { IconName } from '../../components/Icon';
import { GuardBadge, GuardCard, GuardHeading, GuardLink } from '../../components/GuardUI';
import { guardChecklist, guardOfficer, guardPublishedDuties } from '../../data/guardPortal';

export default function GuardHomePage() {
  const nextDuty = guardPublishedDuties.find((duty) => duty.date >= '2026-10-04');
  const published = nextDuty?.publicDuty;
  return <>
    <GuardHeading eyebrow="MY DUTY" title="おはようございます、田中さん" description="会社から公開された、あなたの確定勤務予定を確認しましょう。" action={<span className="gp-date"><Icon name="calendar" size={17} />2026年10月4日（日）</span>} />
    <div className="gp-home-grid"><section className="gp-duty-hero"><div className="gp-hero-top"><span><Icon name="calendar" size={15} />NEXT CONFIRMED DUTY</span><GuardBadge>{published ? '確定・公開中' : '確定予定なし'}</GuardBadge></div>{published && nextDuty ? <><p className="gp-hero-date">次の勤務：2026年10月5日（月）</p><h2>{published.siteName}</h2><p className="gp-hero-client">勤務予定 / 実際の出退勤とは別の情報です</p><div className="gp-hero-hours">{published.startAt.slice(11)}<span>—</span>{published.endAt.slice(11)}</div><div className="gp-hero-meeting"><Icon name="map-pin" size={19} /><div><small>集合場所</small><strong>{published.meeting}</strong></div></div><div className="gp-hero-bottom"><span>公開版 v{published.version}</span><a href={`/guard/site?duty=${nextDuty.dutyId}`}>この勤務の現場情報<Icon name="arrow-right" size={17} /></a></div></> : <div className="gp-hero-no-duty"><h2>公開された勤務予定はありません</h2><p>予定の確認は管制へ連絡してください。</p></div>}</section>
      <GuardCard title="本日の勤務予定" icon="calendar" className="gp-home-punch"><GuardBadge tone="gray">公開された確定予定なし</GuardBadge><h3 className="gp-space-top">10月4日（日）</h3><p className="gp-space-top">予定がない表示は、休みの確定を意味しません。勤務予定や変更の確認は管制へ連絡してください。</p><GuardLink href="/guard/schedule" icon="calendar">自分の勤務予定を確認</GuardLink><a className="gp-text-link" href="/guard/contact">管制の連絡先<Icon name="chevron-right" size={14} /></a></GuardCard></div>
    <div className="gp-info-strip"><Icon name="help" size={20} /><div><strong>勤務の確定・変更・取消は、管制からの連絡も確認してください</strong><p>初回は電話などの既存の連絡手段を使います。勤務希望や下書きの配置は確定勤務として表示しません。</p></div></div>
    <div className="gp-quick-grid">{[{ href: '/guard/schedule', title: '勤務予定', text: '日付と対象勤務を選ぶ', icon: 'calendar' }, { href: '/guard/site', title: '現場情報', text: '公開された勤務を確認', icon: 'map-pin' }, { href: '/guard/profile', title: 'マイページ', text: '本人情報・基本資格', icon: 'users' }, { href: '/guard/contact', title: '連絡先', text: '勤務の確認・変更相談', icon: 'headphones' }].map((item) => <a className="gp-quick-card" href={item.href} key={item.href}><span><Icon name={item.icon as IconName} size={22} /></span><strong>{item.title}</strong><small>{item.text}</small><Icon name="arrow-up-right" size={16} /></a>)}</div>
    <div className="gp-two-columns"><GuardCard title="勤務前に確認すること" icon="check-circle"><ol className="gp-bullet-list"><li>勤務日・開始と終了の日時を確認する。</li><li>対象勤務の集合場所・業務指示を確認する。</li><li>勤務できない・遅れそうな場合は早めに管制へ連絡する。</li></ol><p className="gp-muted gp-space-top">指示の確認や勤務可否は、会社の連絡手順に沿って伝えてください。</p></GuardCard>
      <GuardCard title="出発前の持ち物チェック" icon="shield" action={<span className="gp-muted">手元の確認用</span>}><div className="gp-checklist gp-checklist-vertical">{guardChecklist.map((item) => <label key={item}><input type="checkbox" />{item}</label>)}</div><p className="gp-muted gp-space-top">{guardOfficer.qualifications.join('・')} / チェックはこの画面内のみ有効です。</p></GuardCard></div>
    <GuardCard title="次期機能の参考モック" icon="edit" action={<GuardBadge tone="gray">初回対象外</GuardBadge>}><p className="gp-muted">勤務希望・出退勤・報告・申請の画面は、今後の見た目の確認用に残しています。保存や提出は行いません。</p><div className="gp-reference-links gp-space-top"><GuardLink href="/guard/shifts" secondary>勤務希望</GuardLink><GuardLink href="/guard/attendance" secondary>出退勤</GuardLink><GuardLink href="/guard/reports" secondary>日報・申し送り</GuardLink><GuardLink href="/guard/requests" secondary>各種申請</GuardLink></div></GuardCard>
  </>;
}
