import { useState } from 'react';
import Icon from '../../components/Icon';
import { GuardBadge, GuardCard, GuardHeading, GuardLink, GuardMockButton } from '../../components/GuardUI';
import { attendanceStatuses, formatDuration } from '../../data/attendance';
import { guardAttendance, guardDutySummaries, guardPublishedDuties, guardSchedule, guardSite, guardToday } from '../../data/guardPortal';
import { formatDutyDateTime } from '../../data/mockDutySlots';

const dutyStatusLabels = { published: '確定・公開中', completed: '予定終了', cancelled: '取消済み' };

export function GuardSchedulePage() {
  const requestedDate = new URLSearchParams(window.location.search).get('date');
  const [selected, setSelected] = useState<string>(guardSchedule.some((item) => item.date === requestedDate) ? requestedDate! : '2026-10-04');
  const day = guardSchedule.find((item) => item.date === selected)!;
  return <><GuardHeading eyebrow="MY SCHEDULE" title="勤務予定" description="本人の確定勤務と、終了・取消された予定の概要を確認できます。" action={<GuardLink href="/guard/contact" secondary icon="phone">勤務の確認・変更相談</GuardLink>} />
    <div className="gp-schedule-summary"><div><span>本日 10/4（日）</span><strong>確定予定なし</strong><small>休みが確定したという意味ではありません</small></div><div><span>次の確定勤務</span><strong>10/5（月）09:00</strong><small>18:00まで / 公開された予定の表示例</small></div><div><span>予定と勤務実績</span><strong>別の情報です</strong><small>予定開始だけで勤務中とは表示しません</small></div></div>
    <GuardCard title="10月3日 — 10月10日" icon="calendar"><div className="gp-day-picker" role="group" aria-label="勤務日を選択">{guardSchedule.map((item) => <button type="button" key={item.date} onClick={() => setSelected(item.date)} aria-pressed={selected === item.date} className={selected === item.date ? 'gp-selected' : ''}><span>{item.weekday}</span><strong>{Number(item.date.slice(-2))}</strong><small>{item.date === '2026-10-04' ? '基準日' : item.duties.some((duty) => duty.status === 'published') ? '確定' : item.duties.some((duty) => duty.status === 'cancelled') ? '取消' : item.duties.length ? '終了' : '予定なし'}</small></button>)}</div></GuardCard>
    <div className="gp-two-columns"><GuardCard title={`${day.date.replaceAll('-', '/')}（${day.weekday}）`} icon="calendar">{day.duties.length ? day.duties.map((duty) => <div className="gp-selected-duty" key={duty.dutyId}><GuardBadge tone={duty.status === 'published' ? 'green' : duty.status === 'cancelled' ? 'amber' : 'gray'}>{dutyStatusLabels[duty.status]}</GuardBadge><h3>{duty.siteName}</h3><p>{formatDutyDateTime(duty.startAt)} — {formatDutyDateTime(duty.endAt)}</p>{duty.publicDuty ? <><dl className="gp-facts"><div><dt>集合場所</dt><dd>{duty.publicDuty.meeting}</dd></div><div><dt>公開版</dt><dd>v{duty.publicDuty.version} / 更新 {formatDutyDateTime(duty.publicDuty.updatedAt)}</dd></div></dl><GuardLink href={`/guard/site?duty=${duty.dutyId}`}>この勤務の現場情報を見る</GuardLink></> : <p className="gp-muted gp-space-top">{duty.status === 'cancelled' ? '取消された勤務予定の概要です。管制からの連絡も確認してください。' : '終了した勤務予定の概要です。勤務実績とは別の情報です。'}集合場所・指示・業務連絡先の詳細は表示しません。</p>}</div>) : <div className="gp-empty"><Icon name="calendar" size={31} /><h3>公開された確定勤務はありません</h3><p>勤務希望や調整中の配置は表示しません。<br />予定の確認は管制へ連絡してください。</p><GuardLink href="/guard/contact" secondary>管制の連絡先</GuardLink></div>}</GuardCard>
      <GuardCard title="勤務の一覧" icon="building"><div className="gp-agenda">{guardSchedule.map((item) => <button key={item.date} type="button" onClick={() => setSelected(item.date)} aria-pressed={selected === item.date} className={selected === item.date ? 'gp-selected' : ''}><span className="gp-agenda-date"><strong>10/{Number(item.date.slice(-2))}</strong><small>{item.weekday}</small></span><span><strong>{item.duties.length ? item.duties.map((duty) => duty.siteName).join(' / ') : '公開された確定予定なし'}</strong><small>{item.duties.length ? item.duties.map((duty) => `${duty.startAt.slice(11)} — ${duty.endAt.slice(11)} / ${dutyStatusLabels[duty.status]}`).join(' / ') : '勤務希望・下書きは含みません'}</small></span><Icon name="chevron-right" size={17} /></button>)}</div></GuardCard></div><div className="gp-info-strip"><Icon name="help" size={18} /><p>確定・変更・取消の連絡は電話などの既存の手段で確認してください。アプリ内の通知・既読送信は次期の参考モックです。</p></div></>;
}

export function GuardSitePage() {
  const dutyId = new URLSearchParams(window.location.search).get('duty');
  const duty = guardDutySummaries.find((item) => item.dutyId === dutyId);
  const published = duty?.publicDuty;
  if (!published || !duty) return <>
    <GuardHeading eyebrow="SITE BRIEFING" title="現場情報" description="確定した本人の勤務を選んで、集合場所・指示・業務連絡先を確認します。" action={<GuardLink href={duty ? `/guard/schedule?date=${duty.date}` : '/guard/schedule'} secondary icon="calendar">勤務予定へ</GuardLink>} />
    <GuardCard title={duty?.status === 'cancelled' ? 'この勤務予定は取消されています' : duty?.status === 'completed' ? 'この予定は終了しています' : dutyId ? 'この勤務の現場情報は表示できません' : '対象の勤務を選択'} icon="calendar">
      {duty && duty.status !== 'published' && <div className="gp-selected-duty"><GuardBadge tone={duty.status === 'cancelled' ? 'amber' : 'gray'}>{dutyStatusLabels[duty.status]}</GuardBadge><h3>{duty.siteName}</h3><p>{formatDutyDateTime(duty.startAt)} — {formatDutyDateTime(duty.endAt)}</p></div>}
      <div className="gp-empty"><Icon name="map-pin" size={30} /><p>{duty && duty.status !== 'published' ? '終了・取消された勤務は概要のみを表示します。集合場所・業務指示・現場連絡先の詳細は表示しません。' : dutyId ? '本人に公開された勤務予定から、対象の勤務を選んでください。' : '本日10/4に公開された確定勤務はありません。次の確定勤務の情報を確認できます。'}</p></div>
      {guardPublishedDuties.map((item) => <div className="gp-duty-choice" key={item.dutyId}><div><GuardBadge>確定・公開中</GuardBadge><h3>{item.siteName}</h3><p>{formatDutyDateTime(item.startAt)} — {formatDutyDateTime(item.endAt)}</p></div><GuardLink href={`/guard/site?duty=${item.dutyId}`}>この勤務を開く</GuardLink></div>)}
    </GuardCard></>;
  return <><GuardHeading eyebrow="SITE BRIEFING" title="現場情報" description="集合場所、業務内容、連絡先を勤務前に確認してください。" action={<GuardLink href={`/guard/schedule?date=${duty.date}`} secondary icon="calendar">勤務予定へ</GuardLink>} />
    <div className="gp-site-heading"><span className="gp-site-icon"><Icon name="map-pin" size={30} /></span><div><GuardBadge>確定・公開中</GuardBadge><h2>{published.siteName}</h2><p>{formatDutyDateTime(published.startAt)} — {formatDutyDateTime(published.endAt)}</p></div></div>
    <div className="gp-two-columns"><GuardCard title="この勤務の日時・集合場所" icon="map-pin"><dl className="gp-facts"><div><dt>勤務開始</dt><dd>{published.startAt.replace('T', ' ').replaceAll('-', '/')}</dd></div><div><dt>勤務終了</dt><dd>{published.endAt.replace('T', ' ').replaceAll('-', '/')}</dd></div><div><dt>集合場所</dt><dd>{published.meeting}</dd></div><div><dt>公開版</dt><dd>v{published.version}</dd></div><div><dt>更新日時</dt><dd>{published.updatedAt.replace('T', ' ').replaceAll('-', '/')}</dd></div></dl><p className="gp-muted">勤務予定の表示です。上番・下番や実際の勤務状態を示すものではありません。</p></GuardCard>
      <div className="gp-stack"><GuardCard title="この勤務の公開指示" icon="shield"><p className="gp-body-copy">{published.instruction}</p><ul className="gp-bullet-list"><li>勤務前に集合場所と指示を確認してください。</li><li>勤務できない・変更が必要な場合は管制へ連絡してください。</li></ul><p className="gp-muted gp-space-top">確認の連絡は、会社の電話などの既存の手順を使います。</p></GuardCard><GuardCard title="業務連絡先" icon="phone"><div className="gp-contact-row"><span className="gp-task-icon"><Icon name="phone" size={20} /></span><div><strong>{published.contact}</strong><small>{published.phone} / 架空の連絡先</small></div></div><GuardLink href={`/guard/contact?duty=${duty.dutyId}`} secondary icon="phone">管制・この勤務の連絡先</GuardLink></GuardCard></div></div>
    <div className="gp-info-strip"><Icon name="help" size={18} /><p>選択した勤務の公開情報を表示しています。取消・担当解除・予定終了後は、勤務概要だけを残す画面案です。現場情報の閲覧期間は要件確認前の案です。</p></div></>;
}

export function GuardAttendancePage() {
  const [tab, setTab] = useState('today');
  return <><GuardHeading eyebrow="TIME & ATTENDANCE" title="出退勤・勤務実績" description="上番・下番の報告と、自分の勤務記録を確認できます。" action={<GuardLink href="/guard/requests?kind=correction" secondary icon="edit">打刻修正を申請</GuardLink>} />
    <div className="gp-tabs" role="group" aria-label="勤怠の表示">{[{ id: 'today', text: '本日の出退勤' }, { id: 'history', text: '勤務実績' }].map((item) => <button type="button" key={item.id} aria-pressed={tab === item.id} className={tab === item.id ? 'gp-selected' : ''} onClick={() => setTab(item.id)}>{item.text}</button>)}</div>
    {tab === 'today' ? <div className="gp-two-columns"><GuardCard title="10月4日（日）の勤務" icon="clock"><div className="gp-clock-display"><GuardBadge>勤務中</GuardBadge><strong>09:30</strong><span>基準日時の表示 / 現在時刻には連動しません</span></div><h3 className="gp-centered">{guardSite.name}</h3><div className="gp-time-pair"><div><span>上番予定</span><strong>{guardToday.scheduledStart}</strong></div><div><span>下番予定</span><strong>{guardToday.scheduledEnd}</strong></div></div><div className="gp-punch-buttons"><button type="button" className="gp-button gp-button-secondary" disabled><Icon name="check-circle" size={18} />上番報告済み {guardToday.clockIn}</button><GuardMockButton><Icon name="clock" size={18} />下番を報告（モック）</GuardMockButton></div><p className="gp-form-note">位置情報の取得・打刻送信は行いません。</p></GuardCard><div className="gp-stack"><GuardCard title="本日の記録" icon="activity"><ol className="gp-timeline"><li><strong>09:00</strong><div><h3>上番予定</h3><p>配置された勤務の開始時刻</p></div></li><li><strong>{guardToday.clockIn}</strong><div><h3>上番記録</h3><p>勤務開始の報告サンプル</p><GuardBadge tone="amber">時刻の確認待ち</GuardBadge></div></li><li className="gp-timeline-future"><strong>—</strong><div><h3>休憩・下番</h3><p>休憩予定60分 / 下番は未報告</p></div></li></ol></GuardCard><GuardCard title="休憩時間" icon="clock"><label className="gp-field">休憩時間（分）<input type="number" min="0" max="540" defaultValue={guardToday.breakMinutes} /></label><GuardMockButton secondary>休憩を記録（モック）</GuardMockButton><p className="gp-muted gp-space-top">入力値は実績や管理画面には反映されません。</p></GuardCard></div></div> : <><div className="gp-info-strip"><Icon name="help" size={18} /><p>10月3日・4日の2日分のサンプルです。未下番の勤務は集計前として表示します。</p></div><GuardCard title="勤務記録" icon="calendar"><div className="gp-table-scroll"><table className="gp-table"><thead><tr><th scope="col">勤務日・現場</th><th scope="col">上番</th><th scope="col">下番</th><th scope="col">休憩</th><th scope="col">実績</th><th scope="col">状態</th></tr></thead><tbody>{[...guardAttendance].reverse().map((record) => <tr key={record.id}><td><strong>{record.date.replaceAll('-', '/')}</strong><span>{record.siteName}</span></td><td>{record.clockIn ?? '—'}</td><td>{record.clockOut ?? '—'}</td><td>{record.breakMinutes}分</td><td>{record.actualMinutes === null ? '集計前' : formatDuration(record.actualMinutes)}</td><td><GuardBadge tone={attendanceStatuses[record.status].tone}>{attendanceStatuses[record.status].label}</GuardBadge></td></tr>)}</tbody></table></div></GuardCard><GuardCard title="記録内容の確認" icon="help"><p className="gp-body-copy">{guardToday.reviewNote}</p><GuardLink href="/guard/requests?kind=correction" secondary>打刻修正の申請画面へ</GuardLink></GuardCard></>}
  </>;
}
